//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bangboo_WS.Customer_Service {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VO_Customers", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class VO_Customers : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ID_CustomerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        private int Address_IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID_Customer {
            get {
                return this.ID_CustomerField;
            }
            set {
                if ((this.ID_CustomerField.Equals(value) != true)) {
                    this.ID_CustomerField = value;
                    this.RaisePropertyChanged("ID_Customer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int Address_ID {
            get {
                return this.Address_IDField;
            }
            set {
                if ((this.Address_IDField.Equals(value) != true)) {
                    this.Address_IDField = value;
                    this.RaisePropertyChanged("Address_ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfAnyType", Namespace="http://tempuri.org/", ItemName="anyType")]
    [System.SerializableAttribute()]
    public class ArrayOfAnyType : System.Collections.Generic.List<object> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KeyValuePairOfInt32String", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class KeyValuePairOfInt32String : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Customer_Service.Customer_ServiceSoap")]
    public interface Customer_ServiceSoap {
        
        // CODEGEN: Generating message contract since element name customer from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateCustomer", ReplyAction="*")]
        Bangboo_WS.Customer_Service.CreateCustomerResponse CreateCustomer(Bangboo_WS.Customer_Service.CreateCustomerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateCustomer", ReplyAction="*")]
        System.Threading.Tasks.Task<Bangboo_WS.Customer_Service.CreateCustomerResponse> CreateCustomerAsync(Bangboo_WS.Customer_Service.CreateCustomerRequest request);
        
        // CODEGEN: Generating message contract since element name parameters from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCustomers", ReplyAction="*")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Bangboo_WS.Customer_Service.VO_Customers))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Bangboo_WS.Customer_Service.ArrayOfAnyType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Bangboo_WS.Customer_Service.VO_Customers[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Bangboo_WS.Customer_Service.KeyValuePairOfInt32String))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Bangboo_WS.Customer_Service.KeyValuePairOfInt32String[]))]
        Bangboo_WS.Customer_Service.GetCustomersResponse GetCustomers(Bangboo_WS.Customer_Service.GetCustomersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCustomers", ReplyAction="*")]
        System.Threading.Tasks.Task<Bangboo_WS.Customer_Service.GetCustomersResponse> GetCustomersAsync(Bangboo_WS.Customer_Service.GetCustomersRequest request);
        
        // CODEGEN: Generating message contract since element name parameters from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCustomerNames", ReplyAction="*")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Bangboo_WS.Customer_Service.VO_Customers))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Bangboo_WS.Customer_Service.ArrayOfAnyType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Bangboo_WS.Customer_Service.VO_Customers[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Bangboo_WS.Customer_Service.KeyValuePairOfInt32String))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Bangboo_WS.Customer_Service.KeyValuePairOfInt32String[]))]
        Bangboo_WS.Customer_Service.GetCustomerNamesResponse GetCustomerNames(Bangboo_WS.Customer_Service.GetCustomerNamesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCustomerNames", ReplyAction="*")]
        System.Threading.Tasks.Task<Bangboo_WS.Customer_Service.GetCustomerNamesResponse> GetCustomerNamesAsync(Bangboo_WS.Customer_Service.GetCustomerNamesRequest request);
        
        // CODEGEN: Generating message contract since element name customer from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateCustomer", ReplyAction="*")]
        Bangboo_WS.Customer_Service.UpdateCustomerResponse UpdateCustomer(Bangboo_WS.Customer_Service.UpdateCustomerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateCustomer", ReplyAction="*")]
        System.Threading.Tasks.Task<Bangboo_WS.Customer_Service.UpdateCustomerResponse> UpdateCustomerAsync(Bangboo_WS.Customer_Service.UpdateCustomerRequest request);
        
        // CODEGEN: Generating message contract since element name DeleteCustomerResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteCustomer", ReplyAction="*")]
        Bangboo_WS.Customer_Service.DeleteCustomerResponse DeleteCustomer(Bangboo_WS.Customer_Service.DeleteCustomerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteCustomer", ReplyAction="*")]
        System.Threading.Tasks.Task<Bangboo_WS.Customer_Service.DeleteCustomerResponse> DeleteCustomerAsync(Bangboo_WS.Customer_Service.DeleteCustomerRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateCustomerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateCustomer", Namespace="http://tempuri.org/", Order=0)]
        public Bangboo_WS.Customer_Service.CreateCustomerRequestBody Body;
        
        public CreateCustomerRequest() {
        }
        
        public CreateCustomerRequest(Bangboo_WS.Customer_Service.CreateCustomerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateCustomerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Bangboo_WS.Customer_Service.VO_Customers customer;
        
        public CreateCustomerRequestBody() {
        }
        
        public CreateCustomerRequestBody(Bangboo_WS.Customer_Service.VO_Customers customer) {
            this.customer = customer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateCustomerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateCustomerResponse", Namespace="http://tempuri.org/", Order=0)]
        public Bangboo_WS.Customer_Service.CreateCustomerResponseBody Body;
        
        public CreateCustomerResponse() {
        }
        
        public CreateCustomerResponse(Bangboo_WS.Customer_Service.CreateCustomerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateCustomerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CreateCustomerResult;
        
        public CreateCustomerResponseBody() {
        }
        
        public CreateCustomerResponseBody(string CreateCustomerResult) {
            this.CreateCustomerResult = CreateCustomerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCustomersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCustomers", Namespace="http://tempuri.org/", Order=0)]
        public Bangboo_WS.Customer_Service.GetCustomersRequestBody Body;
        
        public GetCustomersRequest() {
        }
        
        public GetCustomersRequest(Bangboo_WS.Customer_Service.GetCustomersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCustomersRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Bangboo_WS.Customer_Service.ArrayOfAnyType parameters;
        
        public GetCustomersRequestBody() {
        }
        
        public GetCustomersRequestBody(Bangboo_WS.Customer_Service.ArrayOfAnyType parameters) {
            this.parameters = parameters;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCustomersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCustomersResponse", Namespace="http://tempuri.org/", Order=0)]
        public Bangboo_WS.Customer_Service.GetCustomersResponseBody Body;
        
        public GetCustomersResponse() {
        }
        
        public GetCustomersResponse(Bangboo_WS.Customer_Service.GetCustomersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCustomersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Bangboo_WS.Customer_Service.VO_Customers[] GetCustomersResult;
        
        public GetCustomersResponseBody() {
        }
        
        public GetCustomersResponseBody(Bangboo_WS.Customer_Service.VO_Customers[] GetCustomersResult) {
            this.GetCustomersResult = GetCustomersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCustomerNamesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCustomerNames", Namespace="http://tempuri.org/", Order=0)]
        public Bangboo_WS.Customer_Service.GetCustomerNamesRequestBody Body;
        
        public GetCustomerNamesRequest() {
        }
        
        public GetCustomerNamesRequest(Bangboo_WS.Customer_Service.GetCustomerNamesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCustomerNamesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Bangboo_WS.Customer_Service.ArrayOfAnyType parameters;
        
        public GetCustomerNamesRequestBody() {
        }
        
        public GetCustomerNamesRequestBody(Bangboo_WS.Customer_Service.ArrayOfAnyType parameters) {
            this.parameters = parameters;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCustomerNamesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCustomerNamesResponse", Namespace="http://tempuri.org/", Order=0)]
        public Bangboo_WS.Customer_Service.GetCustomerNamesResponseBody Body;
        
        public GetCustomerNamesResponse() {
        }
        
        public GetCustomerNamesResponse(Bangboo_WS.Customer_Service.GetCustomerNamesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCustomerNamesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Bangboo_WS.Customer_Service.KeyValuePairOfInt32String[] GetCustomerNamesResult;
        
        public GetCustomerNamesResponseBody() {
        }
        
        public GetCustomerNamesResponseBody(Bangboo_WS.Customer_Service.KeyValuePairOfInt32String[] GetCustomerNamesResult) {
            this.GetCustomerNamesResult = GetCustomerNamesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateCustomerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateCustomer", Namespace="http://tempuri.org/", Order=0)]
        public Bangboo_WS.Customer_Service.UpdateCustomerRequestBody Body;
        
        public UpdateCustomerRequest() {
        }
        
        public UpdateCustomerRequest(Bangboo_WS.Customer_Service.UpdateCustomerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateCustomerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Bangboo_WS.Customer_Service.VO_Customers customer;
        
        public UpdateCustomerRequestBody() {
        }
        
        public UpdateCustomerRequestBody(Bangboo_WS.Customer_Service.VO_Customers customer) {
            this.customer = customer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateCustomerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateCustomerResponse", Namespace="http://tempuri.org/", Order=0)]
        public Bangboo_WS.Customer_Service.UpdateCustomerResponseBody Body;
        
        public UpdateCustomerResponse() {
        }
        
        public UpdateCustomerResponse(Bangboo_WS.Customer_Service.UpdateCustomerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateCustomerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpdateCustomerResult;
        
        public UpdateCustomerResponseBody() {
        }
        
        public UpdateCustomerResponseBody(string UpdateCustomerResult) {
            this.UpdateCustomerResult = UpdateCustomerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteCustomerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteCustomer", Namespace="http://tempuri.org/", Order=0)]
        public Bangboo_WS.Customer_Service.DeleteCustomerRequestBody Body;
        
        public DeleteCustomerRequest() {
        }
        
        public DeleteCustomerRequest(Bangboo_WS.Customer_Service.DeleteCustomerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteCustomerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public DeleteCustomerRequestBody() {
        }
        
        public DeleteCustomerRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteCustomerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteCustomerResponse", Namespace="http://tempuri.org/", Order=0)]
        public Bangboo_WS.Customer_Service.DeleteCustomerResponseBody Body;
        
        public DeleteCustomerResponse() {
        }
        
        public DeleteCustomerResponse(Bangboo_WS.Customer_Service.DeleteCustomerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteCustomerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DeleteCustomerResult;
        
        public DeleteCustomerResponseBody() {
        }
        
        public DeleteCustomerResponseBody(string DeleteCustomerResult) {
            this.DeleteCustomerResult = DeleteCustomerResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Customer_ServiceSoapChannel : Bangboo_WS.Customer_Service.Customer_ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Customer_ServiceSoapClient : System.ServiceModel.ClientBase<Bangboo_WS.Customer_Service.Customer_ServiceSoap>, Bangboo_WS.Customer_Service.Customer_ServiceSoap {
        
        public Customer_ServiceSoapClient() {
        }
        
        public Customer_ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Customer_ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Customer_ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Customer_ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bangboo_WS.Customer_Service.CreateCustomerResponse Bangboo_WS.Customer_Service.Customer_ServiceSoap.CreateCustomer(Bangboo_WS.Customer_Service.CreateCustomerRequest request) {
            return base.Channel.CreateCustomer(request);
        }
        
        public string CreateCustomer(Bangboo_WS.Customer_Service.VO_Customers customer) {
            Bangboo_WS.Customer_Service.CreateCustomerRequest inValue = new Bangboo_WS.Customer_Service.CreateCustomerRequest();
            inValue.Body = new Bangboo_WS.Customer_Service.CreateCustomerRequestBody();
            inValue.Body.customer = customer;
            Bangboo_WS.Customer_Service.CreateCustomerResponse retVal = ((Bangboo_WS.Customer_Service.Customer_ServiceSoap)(this)).CreateCustomer(inValue);
            return retVal.Body.CreateCustomerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Bangboo_WS.Customer_Service.CreateCustomerResponse> Bangboo_WS.Customer_Service.Customer_ServiceSoap.CreateCustomerAsync(Bangboo_WS.Customer_Service.CreateCustomerRequest request) {
            return base.Channel.CreateCustomerAsync(request);
        }
        
        public System.Threading.Tasks.Task<Bangboo_WS.Customer_Service.CreateCustomerResponse> CreateCustomerAsync(Bangboo_WS.Customer_Service.VO_Customers customer) {
            Bangboo_WS.Customer_Service.CreateCustomerRequest inValue = new Bangboo_WS.Customer_Service.CreateCustomerRequest();
            inValue.Body = new Bangboo_WS.Customer_Service.CreateCustomerRequestBody();
            inValue.Body.customer = customer;
            return ((Bangboo_WS.Customer_Service.Customer_ServiceSoap)(this)).CreateCustomerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bangboo_WS.Customer_Service.GetCustomersResponse Bangboo_WS.Customer_Service.Customer_ServiceSoap.GetCustomers(Bangboo_WS.Customer_Service.GetCustomersRequest request) {
            return base.Channel.GetCustomers(request);
        }
        
        public Bangboo_WS.Customer_Service.VO_Customers[] GetCustomers(Bangboo_WS.Customer_Service.ArrayOfAnyType parameters) {
            Bangboo_WS.Customer_Service.GetCustomersRequest inValue = new Bangboo_WS.Customer_Service.GetCustomersRequest();
            inValue.Body = new Bangboo_WS.Customer_Service.GetCustomersRequestBody();
            inValue.Body.parameters = parameters;
            Bangboo_WS.Customer_Service.GetCustomersResponse retVal = ((Bangboo_WS.Customer_Service.Customer_ServiceSoap)(this)).GetCustomers(inValue);
            return retVal.Body.GetCustomersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Bangboo_WS.Customer_Service.GetCustomersResponse> Bangboo_WS.Customer_Service.Customer_ServiceSoap.GetCustomersAsync(Bangboo_WS.Customer_Service.GetCustomersRequest request) {
            return base.Channel.GetCustomersAsync(request);
        }
        
        public System.Threading.Tasks.Task<Bangboo_WS.Customer_Service.GetCustomersResponse> GetCustomersAsync(Bangboo_WS.Customer_Service.ArrayOfAnyType parameters) {
            Bangboo_WS.Customer_Service.GetCustomersRequest inValue = new Bangboo_WS.Customer_Service.GetCustomersRequest();
            inValue.Body = new Bangboo_WS.Customer_Service.GetCustomersRequestBody();
            inValue.Body.parameters = parameters;
            return ((Bangboo_WS.Customer_Service.Customer_ServiceSoap)(this)).GetCustomersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bangboo_WS.Customer_Service.GetCustomerNamesResponse Bangboo_WS.Customer_Service.Customer_ServiceSoap.GetCustomerNames(Bangboo_WS.Customer_Service.GetCustomerNamesRequest request) {
            return base.Channel.GetCustomerNames(request);
        }
        
        public Bangboo_WS.Customer_Service.KeyValuePairOfInt32String[] GetCustomerNames(Bangboo_WS.Customer_Service.ArrayOfAnyType parameters) {
            Bangboo_WS.Customer_Service.GetCustomerNamesRequest inValue = new Bangboo_WS.Customer_Service.GetCustomerNamesRequest();
            inValue.Body = new Bangboo_WS.Customer_Service.GetCustomerNamesRequestBody();
            inValue.Body.parameters = parameters;
            Bangboo_WS.Customer_Service.GetCustomerNamesResponse retVal = ((Bangboo_WS.Customer_Service.Customer_ServiceSoap)(this)).GetCustomerNames(inValue);
            return retVal.Body.GetCustomerNamesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Bangboo_WS.Customer_Service.GetCustomerNamesResponse> Bangboo_WS.Customer_Service.Customer_ServiceSoap.GetCustomerNamesAsync(Bangboo_WS.Customer_Service.GetCustomerNamesRequest request) {
            return base.Channel.GetCustomerNamesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Bangboo_WS.Customer_Service.GetCustomerNamesResponse> GetCustomerNamesAsync(Bangboo_WS.Customer_Service.ArrayOfAnyType parameters) {
            Bangboo_WS.Customer_Service.GetCustomerNamesRequest inValue = new Bangboo_WS.Customer_Service.GetCustomerNamesRequest();
            inValue.Body = new Bangboo_WS.Customer_Service.GetCustomerNamesRequestBody();
            inValue.Body.parameters = parameters;
            return ((Bangboo_WS.Customer_Service.Customer_ServiceSoap)(this)).GetCustomerNamesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bangboo_WS.Customer_Service.UpdateCustomerResponse Bangboo_WS.Customer_Service.Customer_ServiceSoap.UpdateCustomer(Bangboo_WS.Customer_Service.UpdateCustomerRequest request) {
            return base.Channel.UpdateCustomer(request);
        }
        
        public string UpdateCustomer(Bangboo_WS.Customer_Service.VO_Customers customer) {
            Bangboo_WS.Customer_Service.UpdateCustomerRequest inValue = new Bangboo_WS.Customer_Service.UpdateCustomerRequest();
            inValue.Body = new Bangboo_WS.Customer_Service.UpdateCustomerRequestBody();
            inValue.Body.customer = customer;
            Bangboo_WS.Customer_Service.UpdateCustomerResponse retVal = ((Bangboo_WS.Customer_Service.Customer_ServiceSoap)(this)).UpdateCustomer(inValue);
            return retVal.Body.UpdateCustomerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Bangboo_WS.Customer_Service.UpdateCustomerResponse> Bangboo_WS.Customer_Service.Customer_ServiceSoap.UpdateCustomerAsync(Bangboo_WS.Customer_Service.UpdateCustomerRequest request) {
            return base.Channel.UpdateCustomerAsync(request);
        }
        
        public System.Threading.Tasks.Task<Bangboo_WS.Customer_Service.UpdateCustomerResponse> UpdateCustomerAsync(Bangboo_WS.Customer_Service.VO_Customers customer) {
            Bangboo_WS.Customer_Service.UpdateCustomerRequest inValue = new Bangboo_WS.Customer_Service.UpdateCustomerRequest();
            inValue.Body = new Bangboo_WS.Customer_Service.UpdateCustomerRequestBody();
            inValue.Body.customer = customer;
            return ((Bangboo_WS.Customer_Service.Customer_ServiceSoap)(this)).UpdateCustomerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bangboo_WS.Customer_Service.DeleteCustomerResponse Bangboo_WS.Customer_Service.Customer_ServiceSoap.DeleteCustomer(Bangboo_WS.Customer_Service.DeleteCustomerRequest request) {
            return base.Channel.DeleteCustomer(request);
        }
        
        public string DeleteCustomer(int id) {
            Bangboo_WS.Customer_Service.DeleteCustomerRequest inValue = new Bangboo_WS.Customer_Service.DeleteCustomerRequest();
            inValue.Body = new Bangboo_WS.Customer_Service.DeleteCustomerRequestBody();
            inValue.Body.id = id;
            Bangboo_WS.Customer_Service.DeleteCustomerResponse retVal = ((Bangboo_WS.Customer_Service.Customer_ServiceSoap)(this)).DeleteCustomer(inValue);
            return retVal.Body.DeleteCustomerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Bangboo_WS.Customer_Service.DeleteCustomerResponse> Bangboo_WS.Customer_Service.Customer_ServiceSoap.DeleteCustomerAsync(Bangboo_WS.Customer_Service.DeleteCustomerRequest request) {
            return base.Channel.DeleteCustomerAsync(request);
        }
        
        public System.Threading.Tasks.Task<Bangboo_WS.Customer_Service.DeleteCustomerResponse> DeleteCustomerAsync(int id) {
            Bangboo_WS.Customer_Service.DeleteCustomerRequest inValue = new Bangboo_WS.Customer_Service.DeleteCustomerRequest();
            inValue.Body = new Bangboo_WS.Customer_Service.DeleteCustomerRequestBody();
            inValue.Body.id = id;
            return ((Bangboo_WS.Customer_Service.Customer_ServiceSoap)(this)).DeleteCustomerAsync(inValue);
        }
    }
}
