//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bangboo_WS.BangbooSupplier_Service {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VO_BangbooSuppliers", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class VO_BangbooSuppliers : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ID_SupplierField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        private int Address_IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID_Supplier {
            get {
                return this.ID_SupplierField;
            }
            set {
                if ((this.ID_SupplierField.Equals(value) != true)) {
                    this.ID_SupplierField = value;
                    this.RaisePropertyChanged("ID_Supplier");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int Address_ID {
            get {
                return this.Address_IDField;
            }
            set {
                if ((this.Address_IDField.Equals(value) != true)) {
                    this.Address_IDField = value;
                    this.RaisePropertyChanged("Address_ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfAnyType", Namespace="http://tempuri.org/", ItemName="anyType")]
    [System.SerializableAttribute()]
    public class ArrayOfAnyType : System.Collections.Generic.List<object> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BangbooSupplier_Service.BangbooSupplier_ServiceSoap")]
    public interface BangbooSupplier_ServiceSoap {
        
        // CODEGEN: Generating message contract since element name supplier from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateBangbooSupplier", ReplyAction="*")]
        Bangboo_WS.BangbooSupplier_Service.CreateBangbooSupplierResponse CreateBangbooSupplier(Bangboo_WS.BangbooSupplier_Service.CreateBangbooSupplierRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateBangbooSupplier", ReplyAction="*")]
        System.Threading.Tasks.Task<Bangboo_WS.BangbooSupplier_Service.CreateBangbooSupplierResponse> CreateBangbooSupplierAsync(Bangboo_WS.BangbooSupplier_Service.CreateBangbooSupplierRequest request);
        
        // CODEGEN: Generating message contract since element name parameters from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBangbooSuppliers", ReplyAction="*")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Bangboo_WS.BangbooSupplier_Service.VO_BangbooSuppliers))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Bangboo_WS.BangbooSupplier_Service.ArrayOfAnyType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Bangboo_WS.BangbooSupplier_Service.VO_BangbooSuppliers[]))]
        Bangboo_WS.BangbooSupplier_Service.GetBangbooSuppliersResponse GetBangbooSuppliers(Bangboo_WS.BangbooSupplier_Service.GetBangbooSuppliersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBangbooSuppliers", ReplyAction="*")]
        System.Threading.Tasks.Task<Bangboo_WS.BangbooSupplier_Service.GetBangbooSuppliersResponse> GetBangbooSuppliersAsync(Bangboo_WS.BangbooSupplier_Service.GetBangbooSuppliersRequest request);
        
        // CODEGEN: Generating message contract since element name supplier from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateBangbooSupplier", ReplyAction="*")]
        Bangboo_WS.BangbooSupplier_Service.UpdateBangbooSupplierResponse UpdateBangbooSupplier(Bangboo_WS.BangbooSupplier_Service.UpdateBangbooSupplierRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateBangbooSupplier", ReplyAction="*")]
        System.Threading.Tasks.Task<Bangboo_WS.BangbooSupplier_Service.UpdateBangbooSupplierResponse> UpdateBangbooSupplierAsync(Bangboo_WS.BangbooSupplier_Service.UpdateBangbooSupplierRequest request);
        
        // CODEGEN: Generating message contract since element name DeleteSupplierResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteSupplier", ReplyAction="*")]
        Bangboo_WS.BangbooSupplier_Service.DeleteSupplierResponse DeleteSupplier(Bangboo_WS.BangbooSupplier_Service.DeleteSupplierRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteSupplier", ReplyAction="*")]
        System.Threading.Tasks.Task<Bangboo_WS.BangbooSupplier_Service.DeleteSupplierResponse> DeleteSupplierAsync(Bangboo_WS.BangbooSupplier_Service.DeleteSupplierRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateBangbooSupplierRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateBangbooSupplier", Namespace="http://tempuri.org/", Order=0)]
        public Bangboo_WS.BangbooSupplier_Service.CreateBangbooSupplierRequestBody Body;
        
        public CreateBangbooSupplierRequest() {
        }
        
        public CreateBangbooSupplierRequest(Bangboo_WS.BangbooSupplier_Service.CreateBangbooSupplierRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateBangbooSupplierRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Bangboo_WS.BangbooSupplier_Service.VO_BangbooSuppliers supplier;
        
        public CreateBangbooSupplierRequestBody() {
        }
        
        public CreateBangbooSupplierRequestBody(Bangboo_WS.BangbooSupplier_Service.VO_BangbooSuppliers supplier) {
            this.supplier = supplier;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateBangbooSupplierResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateBangbooSupplierResponse", Namespace="http://tempuri.org/", Order=0)]
        public Bangboo_WS.BangbooSupplier_Service.CreateBangbooSupplierResponseBody Body;
        
        public CreateBangbooSupplierResponse() {
        }
        
        public CreateBangbooSupplierResponse(Bangboo_WS.BangbooSupplier_Service.CreateBangbooSupplierResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateBangbooSupplierResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CreateBangbooSupplierResult;
        
        public CreateBangbooSupplierResponseBody() {
        }
        
        public CreateBangbooSupplierResponseBody(string CreateBangbooSupplierResult) {
            this.CreateBangbooSupplierResult = CreateBangbooSupplierResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBangbooSuppliersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBangbooSuppliers", Namespace="http://tempuri.org/", Order=0)]
        public Bangboo_WS.BangbooSupplier_Service.GetBangbooSuppliersRequestBody Body;
        
        public GetBangbooSuppliersRequest() {
        }
        
        public GetBangbooSuppliersRequest(Bangboo_WS.BangbooSupplier_Service.GetBangbooSuppliersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBangbooSuppliersRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Bangboo_WS.BangbooSupplier_Service.ArrayOfAnyType parameters;
        
        public GetBangbooSuppliersRequestBody() {
        }
        
        public GetBangbooSuppliersRequestBody(Bangboo_WS.BangbooSupplier_Service.ArrayOfAnyType parameters) {
            this.parameters = parameters;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBangbooSuppliersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBangbooSuppliersResponse", Namespace="http://tempuri.org/", Order=0)]
        public Bangboo_WS.BangbooSupplier_Service.GetBangbooSuppliersResponseBody Body;
        
        public GetBangbooSuppliersResponse() {
        }
        
        public GetBangbooSuppliersResponse(Bangboo_WS.BangbooSupplier_Service.GetBangbooSuppliersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBangbooSuppliersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Bangboo_WS.BangbooSupplier_Service.VO_BangbooSuppliers[] GetBangbooSuppliersResult;
        
        public GetBangbooSuppliersResponseBody() {
        }
        
        public GetBangbooSuppliersResponseBody(Bangboo_WS.BangbooSupplier_Service.VO_BangbooSuppliers[] GetBangbooSuppliersResult) {
            this.GetBangbooSuppliersResult = GetBangbooSuppliersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateBangbooSupplierRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateBangbooSupplier", Namespace="http://tempuri.org/", Order=0)]
        public Bangboo_WS.BangbooSupplier_Service.UpdateBangbooSupplierRequestBody Body;
        
        public UpdateBangbooSupplierRequest() {
        }
        
        public UpdateBangbooSupplierRequest(Bangboo_WS.BangbooSupplier_Service.UpdateBangbooSupplierRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateBangbooSupplierRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Bangboo_WS.BangbooSupplier_Service.VO_BangbooSuppliers supplier;
        
        public UpdateBangbooSupplierRequestBody() {
        }
        
        public UpdateBangbooSupplierRequestBody(Bangboo_WS.BangbooSupplier_Service.VO_BangbooSuppliers supplier) {
            this.supplier = supplier;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateBangbooSupplierResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateBangbooSupplierResponse", Namespace="http://tempuri.org/", Order=0)]
        public Bangboo_WS.BangbooSupplier_Service.UpdateBangbooSupplierResponseBody Body;
        
        public UpdateBangbooSupplierResponse() {
        }
        
        public UpdateBangbooSupplierResponse(Bangboo_WS.BangbooSupplier_Service.UpdateBangbooSupplierResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateBangbooSupplierResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpdateBangbooSupplierResult;
        
        public UpdateBangbooSupplierResponseBody() {
        }
        
        public UpdateBangbooSupplierResponseBody(string UpdateBangbooSupplierResult) {
            this.UpdateBangbooSupplierResult = UpdateBangbooSupplierResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteSupplierRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteSupplier", Namespace="http://tempuri.org/", Order=0)]
        public Bangboo_WS.BangbooSupplier_Service.DeleteSupplierRequestBody Body;
        
        public DeleteSupplierRequest() {
        }
        
        public DeleteSupplierRequest(Bangboo_WS.BangbooSupplier_Service.DeleteSupplierRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteSupplierRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public DeleteSupplierRequestBody() {
        }
        
        public DeleteSupplierRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteSupplierResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteSupplierResponse", Namespace="http://tempuri.org/", Order=0)]
        public Bangboo_WS.BangbooSupplier_Service.DeleteSupplierResponseBody Body;
        
        public DeleteSupplierResponse() {
        }
        
        public DeleteSupplierResponse(Bangboo_WS.BangbooSupplier_Service.DeleteSupplierResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteSupplierResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DeleteSupplierResult;
        
        public DeleteSupplierResponseBody() {
        }
        
        public DeleteSupplierResponseBody(string DeleteSupplierResult) {
            this.DeleteSupplierResult = DeleteSupplierResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BangbooSupplier_ServiceSoapChannel : Bangboo_WS.BangbooSupplier_Service.BangbooSupplier_ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BangbooSupplier_ServiceSoapClient : System.ServiceModel.ClientBase<Bangboo_WS.BangbooSupplier_Service.BangbooSupplier_ServiceSoap>, Bangboo_WS.BangbooSupplier_Service.BangbooSupplier_ServiceSoap {
        
        public BangbooSupplier_ServiceSoapClient() {
        }
        
        public BangbooSupplier_ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BangbooSupplier_ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BangbooSupplier_ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BangbooSupplier_ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bangboo_WS.BangbooSupplier_Service.CreateBangbooSupplierResponse Bangboo_WS.BangbooSupplier_Service.BangbooSupplier_ServiceSoap.CreateBangbooSupplier(Bangboo_WS.BangbooSupplier_Service.CreateBangbooSupplierRequest request) {
            return base.Channel.CreateBangbooSupplier(request);
        }
        
        public string CreateBangbooSupplier(Bangboo_WS.BangbooSupplier_Service.VO_BangbooSuppliers supplier) {
            Bangboo_WS.BangbooSupplier_Service.CreateBangbooSupplierRequest inValue = new Bangboo_WS.BangbooSupplier_Service.CreateBangbooSupplierRequest();
            inValue.Body = new Bangboo_WS.BangbooSupplier_Service.CreateBangbooSupplierRequestBody();
            inValue.Body.supplier = supplier;
            Bangboo_WS.BangbooSupplier_Service.CreateBangbooSupplierResponse retVal = ((Bangboo_WS.BangbooSupplier_Service.BangbooSupplier_ServiceSoap)(this)).CreateBangbooSupplier(inValue);
            return retVal.Body.CreateBangbooSupplierResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Bangboo_WS.BangbooSupplier_Service.CreateBangbooSupplierResponse> Bangboo_WS.BangbooSupplier_Service.BangbooSupplier_ServiceSoap.CreateBangbooSupplierAsync(Bangboo_WS.BangbooSupplier_Service.CreateBangbooSupplierRequest request) {
            return base.Channel.CreateBangbooSupplierAsync(request);
        }
        
        public System.Threading.Tasks.Task<Bangboo_WS.BangbooSupplier_Service.CreateBangbooSupplierResponse> CreateBangbooSupplierAsync(Bangboo_WS.BangbooSupplier_Service.VO_BangbooSuppliers supplier) {
            Bangboo_WS.BangbooSupplier_Service.CreateBangbooSupplierRequest inValue = new Bangboo_WS.BangbooSupplier_Service.CreateBangbooSupplierRequest();
            inValue.Body = new Bangboo_WS.BangbooSupplier_Service.CreateBangbooSupplierRequestBody();
            inValue.Body.supplier = supplier;
            return ((Bangboo_WS.BangbooSupplier_Service.BangbooSupplier_ServiceSoap)(this)).CreateBangbooSupplierAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bangboo_WS.BangbooSupplier_Service.GetBangbooSuppliersResponse Bangboo_WS.BangbooSupplier_Service.BangbooSupplier_ServiceSoap.GetBangbooSuppliers(Bangboo_WS.BangbooSupplier_Service.GetBangbooSuppliersRequest request) {
            return base.Channel.GetBangbooSuppliers(request);
        }
        
        public Bangboo_WS.BangbooSupplier_Service.VO_BangbooSuppliers[] GetBangbooSuppliers(Bangboo_WS.BangbooSupplier_Service.ArrayOfAnyType parameters) {
            Bangboo_WS.BangbooSupplier_Service.GetBangbooSuppliersRequest inValue = new Bangboo_WS.BangbooSupplier_Service.GetBangbooSuppliersRequest();
            inValue.Body = new Bangboo_WS.BangbooSupplier_Service.GetBangbooSuppliersRequestBody();
            inValue.Body.parameters = parameters;
            Bangboo_WS.BangbooSupplier_Service.GetBangbooSuppliersResponse retVal = ((Bangboo_WS.BangbooSupplier_Service.BangbooSupplier_ServiceSoap)(this)).GetBangbooSuppliers(inValue);
            return retVal.Body.GetBangbooSuppliersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Bangboo_WS.BangbooSupplier_Service.GetBangbooSuppliersResponse> Bangboo_WS.BangbooSupplier_Service.BangbooSupplier_ServiceSoap.GetBangbooSuppliersAsync(Bangboo_WS.BangbooSupplier_Service.GetBangbooSuppliersRequest request) {
            return base.Channel.GetBangbooSuppliersAsync(request);
        }
        
        public System.Threading.Tasks.Task<Bangboo_WS.BangbooSupplier_Service.GetBangbooSuppliersResponse> GetBangbooSuppliersAsync(Bangboo_WS.BangbooSupplier_Service.ArrayOfAnyType parameters) {
            Bangboo_WS.BangbooSupplier_Service.GetBangbooSuppliersRequest inValue = new Bangboo_WS.BangbooSupplier_Service.GetBangbooSuppliersRequest();
            inValue.Body = new Bangboo_WS.BangbooSupplier_Service.GetBangbooSuppliersRequestBody();
            inValue.Body.parameters = parameters;
            return ((Bangboo_WS.BangbooSupplier_Service.BangbooSupplier_ServiceSoap)(this)).GetBangbooSuppliersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bangboo_WS.BangbooSupplier_Service.UpdateBangbooSupplierResponse Bangboo_WS.BangbooSupplier_Service.BangbooSupplier_ServiceSoap.UpdateBangbooSupplier(Bangboo_WS.BangbooSupplier_Service.UpdateBangbooSupplierRequest request) {
            return base.Channel.UpdateBangbooSupplier(request);
        }
        
        public string UpdateBangbooSupplier(Bangboo_WS.BangbooSupplier_Service.VO_BangbooSuppliers supplier) {
            Bangboo_WS.BangbooSupplier_Service.UpdateBangbooSupplierRequest inValue = new Bangboo_WS.BangbooSupplier_Service.UpdateBangbooSupplierRequest();
            inValue.Body = new Bangboo_WS.BangbooSupplier_Service.UpdateBangbooSupplierRequestBody();
            inValue.Body.supplier = supplier;
            Bangboo_WS.BangbooSupplier_Service.UpdateBangbooSupplierResponse retVal = ((Bangboo_WS.BangbooSupplier_Service.BangbooSupplier_ServiceSoap)(this)).UpdateBangbooSupplier(inValue);
            return retVal.Body.UpdateBangbooSupplierResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Bangboo_WS.BangbooSupplier_Service.UpdateBangbooSupplierResponse> Bangboo_WS.BangbooSupplier_Service.BangbooSupplier_ServiceSoap.UpdateBangbooSupplierAsync(Bangboo_WS.BangbooSupplier_Service.UpdateBangbooSupplierRequest request) {
            return base.Channel.UpdateBangbooSupplierAsync(request);
        }
        
        public System.Threading.Tasks.Task<Bangboo_WS.BangbooSupplier_Service.UpdateBangbooSupplierResponse> UpdateBangbooSupplierAsync(Bangboo_WS.BangbooSupplier_Service.VO_BangbooSuppliers supplier) {
            Bangboo_WS.BangbooSupplier_Service.UpdateBangbooSupplierRequest inValue = new Bangboo_WS.BangbooSupplier_Service.UpdateBangbooSupplierRequest();
            inValue.Body = new Bangboo_WS.BangbooSupplier_Service.UpdateBangbooSupplierRequestBody();
            inValue.Body.supplier = supplier;
            return ((Bangboo_WS.BangbooSupplier_Service.BangbooSupplier_ServiceSoap)(this)).UpdateBangbooSupplierAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bangboo_WS.BangbooSupplier_Service.DeleteSupplierResponse Bangboo_WS.BangbooSupplier_Service.BangbooSupplier_ServiceSoap.DeleteSupplier(Bangboo_WS.BangbooSupplier_Service.DeleteSupplierRequest request) {
            return base.Channel.DeleteSupplier(request);
        }
        
        public string DeleteSupplier(int id) {
            Bangboo_WS.BangbooSupplier_Service.DeleteSupplierRequest inValue = new Bangboo_WS.BangbooSupplier_Service.DeleteSupplierRequest();
            inValue.Body = new Bangboo_WS.BangbooSupplier_Service.DeleteSupplierRequestBody();
            inValue.Body.id = id;
            Bangboo_WS.BangbooSupplier_Service.DeleteSupplierResponse retVal = ((Bangboo_WS.BangbooSupplier_Service.BangbooSupplier_ServiceSoap)(this)).DeleteSupplier(inValue);
            return retVal.Body.DeleteSupplierResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Bangboo_WS.BangbooSupplier_Service.DeleteSupplierResponse> Bangboo_WS.BangbooSupplier_Service.BangbooSupplier_ServiceSoap.DeleteSupplierAsync(Bangboo_WS.BangbooSupplier_Service.DeleteSupplierRequest request) {
            return base.Channel.DeleteSupplierAsync(request);
        }
        
        public System.Threading.Tasks.Task<Bangboo_WS.BangbooSupplier_Service.DeleteSupplierResponse> DeleteSupplierAsync(int id) {
            Bangboo_WS.BangbooSupplier_Service.DeleteSupplierRequest inValue = new Bangboo_WS.BangbooSupplier_Service.DeleteSupplierRequest();
            inValue.Body = new Bangboo_WS.BangbooSupplier_Service.DeleteSupplierRequestBody();
            inValue.Body.id = id;
            return ((Bangboo_WS.BangbooSupplier_Service.BangbooSupplier_ServiceSoap)(this)).DeleteSupplierAsync(inValue);
        }
    }
}
