//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bangboo_WS.SalesReceipt_Service {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VO_SalesReceipts", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class VO_SalesReceipts : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ID_SaleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SaleDateField;
        
        private int Employee_IDField;
        
        private int Customer_IDField;
        
        private int TotalAmountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID_Sale {
            get {
                return this.ID_SaleField;
            }
            set {
                if ((this.ID_SaleField.Equals(value) != true)) {
                    this.ID_SaleField = value;
                    this.RaisePropertyChanged("ID_Sale");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SaleDate {
            get {
                return this.SaleDateField;
            }
            set {
                if ((object.ReferenceEquals(this.SaleDateField, value) != true)) {
                    this.SaleDateField = value;
                    this.RaisePropertyChanged("SaleDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int Employee_ID {
            get {
                return this.Employee_IDField;
            }
            set {
                if ((this.Employee_IDField.Equals(value) != true)) {
                    this.Employee_IDField = value;
                    this.RaisePropertyChanged("Employee_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int Customer_ID {
            get {
                return this.Customer_IDField;
            }
            set {
                if ((this.Customer_IDField.Equals(value) != true)) {
                    this.Customer_IDField = value;
                    this.RaisePropertyChanged("Customer_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int TotalAmount {
            get {
                return this.TotalAmountField;
            }
            set {
                if ((this.TotalAmountField.Equals(value) != true)) {
                    this.TotalAmountField = value;
                    this.RaisePropertyChanged("TotalAmount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfAnyType", Namespace="http://tempuri.org/", ItemName="anyType")]
    [System.SerializableAttribute()]
    public class ArrayOfAnyType : System.Collections.Generic.List<object> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SalesReceipt_Service.SalesReceipt_ServiceSoap")]
    public interface SalesReceipt_ServiceSoap {
        
        // CODEGEN: Generating message contract since element name receipt from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateSalesReceipt", ReplyAction="*")]
        Bangboo_WS.SalesReceipt_Service.CreateSalesReceiptResponse CreateSalesReceipt(Bangboo_WS.SalesReceipt_Service.CreateSalesReceiptRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateSalesReceipt", ReplyAction="*")]
        System.Threading.Tasks.Task<Bangboo_WS.SalesReceipt_Service.CreateSalesReceiptResponse> CreateSalesReceiptAsync(Bangboo_WS.SalesReceipt_Service.CreateSalesReceiptRequest request);
        
        // CODEGEN: Generating message contract since element name parameters from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSalesReceipt", ReplyAction="*")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Bangboo_WS.SalesReceipt_Service.VO_SalesReceipts))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Bangboo_WS.SalesReceipt_Service.ArrayOfAnyType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Bangboo_WS.SalesReceipt_Service.VO_SalesReceipts[]))]
        Bangboo_WS.SalesReceipt_Service.GetSalesReceiptResponse GetSalesReceipt(Bangboo_WS.SalesReceipt_Service.GetSalesReceiptRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSalesReceipt", ReplyAction="*")]
        System.Threading.Tasks.Task<Bangboo_WS.SalesReceipt_Service.GetSalesReceiptResponse> GetSalesReceiptAsync(Bangboo_WS.SalesReceipt_Service.GetSalesReceiptRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateSalesReceiptRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateSalesReceipt", Namespace="http://tempuri.org/", Order=0)]
        public Bangboo_WS.SalesReceipt_Service.CreateSalesReceiptRequestBody Body;
        
        public CreateSalesReceiptRequest() {
        }
        
        public CreateSalesReceiptRequest(Bangboo_WS.SalesReceipt_Service.CreateSalesReceiptRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateSalesReceiptRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Bangboo_WS.SalesReceipt_Service.VO_SalesReceipts receipt;
        
        public CreateSalesReceiptRequestBody() {
        }
        
        public CreateSalesReceiptRequestBody(Bangboo_WS.SalesReceipt_Service.VO_SalesReceipts receipt) {
            this.receipt = receipt;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateSalesReceiptResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateSalesReceiptResponse", Namespace="http://tempuri.org/", Order=0)]
        public Bangboo_WS.SalesReceipt_Service.CreateSalesReceiptResponseBody Body;
        
        public CreateSalesReceiptResponse() {
        }
        
        public CreateSalesReceiptResponse(Bangboo_WS.SalesReceipt_Service.CreateSalesReceiptResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateSalesReceiptResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CreateSalesReceiptResult;
        
        public CreateSalesReceiptResponseBody() {
        }
        
        public CreateSalesReceiptResponseBody(string CreateSalesReceiptResult) {
            this.CreateSalesReceiptResult = CreateSalesReceiptResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSalesReceiptRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSalesReceipt", Namespace="http://tempuri.org/", Order=0)]
        public Bangboo_WS.SalesReceipt_Service.GetSalesReceiptRequestBody Body;
        
        public GetSalesReceiptRequest() {
        }
        
        public GetSalesReceiptRequest(Bangboo_WS.SalesReceipt_Service.GetSalesReceiptRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSalesReceiptRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Bangboo_WS.SalesReceipt_Service.ArrayOfAnyType parameters;
        
        public GetSalesReceiptRequestBody() {
        }
        
        public GetSalesReceiptRequestBody(Bangboo_WS.SalesReceipt_Service.ArrayOfAnyType parameters) {
            this.parameters = parameters;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSalesReceiptResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSalesReceiptResponse", Namespace="http://tempuri.org/", Order=0)]
        public Bangboo_WS.SalesReceipt_Service.GetSalesReceiptResponseBody Body;
        
        public GetSalesReceiptResponse() {
        }
        
        public GetSalesReceiptResponse(Bangboo_WS.SalesReceipt_Service.GetSalesReceiptResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSalesReceiptResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Bangboo_WS.SalesReceipt_Service.VO_SalesReceipts[] GetSalesReceiptResult;
        
        public GetSalesReceiptResponseBody() {
        }
        
        public GetSalesReceiptResponseBody(Bangboo_WS.SalesReceipt_Service.VO_SalesReceipts[] GetSalesReceiptResult) {
            this.GetSalesReceiptResult = GetSalesReceiptResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SalesReceipt_ServiceSoapChannel : Bangboo_WS.SalesReceipt_Service.SalesReceipt_ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SalesReceipt_ServiceSoapClient : System.ServiceModel.ClientBase<Bangboo_WS.SalesReceipt_Service.SalesReceipt_ServiceSoap>, Bangboo_WS.SalesReceipt_Service.SalesReceipt_ServiceSoap {
        
        public SalesReceipt_ServiceSoapClient() {
        }
        
        public SalesReceipt_ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SalesReceipt_ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SalesReceipt_ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SalesReceipt_ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bangboo_WS.SalesReceipt_Service.CreateSalesReceiptResponse Bangboo_WS.SalesReceipt_Service.SalesReceipt_ServiceSoap.CreateSalesReceipt(Bangboo_WS.SalesReceipt_Service.CreateSalesReceiptRequest request) {
            return base.Channel.CreateSalesReceipt(request);
        }
        
        public string CreateSalesReceipt(Bangboo_WS.SalesReceipt_Service.VO_SalesReceipts receipt) {
            Bangboo_WS.SalesReceipt_Service.CreateSalesReceiptRequest inValue = new Bangboo_WS.SalesReceipt_Service.CreateSalesReceiptRequest();
            inValue.Body = new Bangboo_WS.SalesReceipt_Service.CreateSalesReceiptRequestBody();
            inValue.Body.receipt = receipt;
            Bangboo_WS.SalesReceipt_Service.CreateSalesReceiptResponse retVal = ((Bangboo_WS.SalesReceipt_Service.SalesReceipt_ServiceSoap)(this)).CreateSalesReceipt(inValue);
            return retVal.Body.CreateSalesReceiptResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Bangboo_WS.SalesReceipt_Service.CreateSalesReceiptResponse> Bangboo_WS.SalesReceipt_Service.SalesReceipt_ServiceSoap.CreateSalesReceiptAsync(Bangboo_WS.SalesReceipt_Service.CreateSalesReceiptRequest request) {
            return base.Channel.CreateSalesReceiptAsync(request);
        }
        
        public System.Threading.Tasks.Task<Bangboo_WS.SalesReceipt_Service.CreateSalesReceiptResponse> CreateSalesReceiptAsync(Bangboo_WS.SalesReceipt_Service.VO_SalesReceipts receipt) {
            Bangboo_WS.SalesReceipt_Service.CreateSalesReceiptRequest inValue = new Bangboo_WS.SalesReceipt_Service.CreateSalesReceiptRequest();
            inValue.Body = new Bangboo_WS.SalesReceipt_Service.CreateSalesReceiptRequestBody();
            inValue.Body.receipt = receipt;
            return ((Bangboo_WS.SalesReceipt_Service.SalesReceipt_ServiceSoap)(this)).CreateSalesReceiptAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bangboo_WS.SalesReceipt_Service.GetSalesReceiptResponse Bangboo_WS.SalesReceipt_Service.SalesReceipt_ServiceSoap.GetSalesReceipt(Bangboo_WS.SalesReceipt_Service.GetSalesReceiptRequest request) {
            return base.Channel.GetSalesReceipt(request);
        }
        
        public Bangboo_WS.SalesReceipt_Service.VO_SalesReceipts[] GetSalesReceipt(Bangboo_WS.SalesReceipt_Service.ArrayOfAnyType parameters) {
            Bangboo_WS.SalesReceipt_Service.GetSalesReceiptRequest inValue = new Bangboo_WS.SalesReceipt_Service.GetSalesReceiptRequest();
            inValue.Body = new Bangboo_WS.SalesReceipt_Service.GetSalesReceiptRequestBody();
            inValue.Body.parameters = parameters;
            Bangboo_WS.SalesReceipt_Service.GetSalesReceiptResponse retVal = ((Bangboo_WS.SalesReceipt_Service.SalesReceipt_ServiceSoap)(this)).GetSalesReceipt(inValue);
            return retVal.Body.GetSalesReceiptResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Bangboo_WS.SalesReceipt_Service.GetSalesReceiptResponse> Bangboo_WS.SalesReceipt_Service.SalesReceipt_ServiceSoap.GetSalesReceiptAsync(Bangboo_WS.SalesReceipt_Service.GetSalesReceiptRequest request) {
            return base.Channel.GetSalesReceiptAsync(request);
        }
        
        public System.Threading.Tasks.Task<Bangboo_WS.SalesReceipt_Service.GetSalesReceiptResponse> GetSalesReceiptAsync(Bangboo_WS.SalesReceipt_Service.ArrayOfAnyType parameters) {
            Bangboo_WS.SalesReceipt_Service.GetSalesReceiptRequest inValue = new Bangboo_WS.SalesReceipt_Service.GetSalesReceiptRequest();
            inValue.Body = new Bangboo_WS.SalesReceipt_Service.GetSalesReceiptRequestBody();
            inValue.Body.parameters = parameters;
            return ((Bangboo_WS.SalesReceipt_Service.SalesReceipt_ServiceSoap)(this)).GetSalesReceiptAsync(inValue);
        }
    }
}
