//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bangboo_WS.Stock_Detail_Service {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfAnyType", Namespace="http://tempuri.org/", ItemName="anyType")]
    [System.SerializableAttribute()]
    public class ArrayOfAnyType : System.Collections.Generic.List<object> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VO_Stock_Details", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class VO_Stock_Details : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ID_DetailField;
        
        private int ID_BangbooField;
        
        private int PriceField;
        
        private int UnitCostField;
        
        private int SupplyAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SupplyDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PictureURLField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID_Detail {
            get {
                return this.ID_DetailField;
            }
            set {
                if ((this.ID_DetailField.Equals(value) != true)) {
                    this.ID_DetailField = value;
                    this.RaisePropertyChanged("ID_Detail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int ID_Bangboo {
            get {
                return this.ID_BangbooField;
            }
            set {
                if ((this.ID_BangbooField.Equals(value) != true)) {
                    this.ID_BangbooField = value;
                    this.RaisePropertyChanged("ID_Bangboo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int UnitCost {
            get {
                return this.UnitCostField;
            }
            set {
                if ((this.UnitCostField.Equals(value) != true)) {
                    this.UnitCostField = value;
                    this.RaisePropertyChanged("UnitCost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int SupplyAmount {
            get {
                return this.SupplyAmountField;
            }
            set {
                if ((this.SupplyAmountField.Equals(value) != true)) {
                    this.SupplyAmountField = value;
                    this.RaisePropertyChanged("SupplyAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string SupplyDate {
            get {
                return this.SupplyDateField;
            }
            set {
                if ((object.ReferenceEquals(this.SupplyDateField, value) != true)) {
                    this.SupplyDateField = value;
                    this.RaisePropertyChanged("SupplyDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string PictureURL {
            get {
                return this.PictureURLField;
            }
            set {
                if ((object.ReferenceEquals(this.PictureURLField, value) != true)) {
                    this.PictureURLField = value;
                    this.RaisePropertyChanged("PictureURL");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Stock_Detail_Service.Stock_Detail_ServiceSoap")]
    public interface Stock_Detail_ServiceSoap {
        
        // CODEGEN: Generating message contract since element name parameters from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStockDetails", ReplyAction="*")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Bangboo_WS.Stock_Detail_Service.ArrayOfAnyType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Bangboo_WS.Stock_Detail_Service.VO_Stock_Details))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Bangboo_WS.Stock_Detail_Service.VO_Stock_Details[]))]
        Bangboo_WS.Stock_Detail_Service.GetStockDetailsResponse GetStockDetails(Bangboo_WS.Stock_Detail_Service.GetStockDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStockDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<Bangboo_WS.Stock_Detail_Service.GetStockDetailsResponse> GetStockDetailsAsync(Bangboo_WS.Stock_Detail_Service.GetStockDetailsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStockDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStockDetails", Namespace="http://tempuri.org/", Order=0)]
        public Bangboo_WS.Stock_Detail_Service.GetStockDetailsRequestBody Body;
        
        public GetStockDetailsRequest() {
        }
        
        public GetStockDetailsRequest(Bangboo_WS.Stock_Detail_Service.GetStockDetailsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStockDetailsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Bangboo_WS.Stock_Detail_Service.ArrayOfAnyType parameters;
        
        public GetStockDetailsRequestBody() {
        }
        
        public GetStockDetailsRequestBody(Bangboo_WS.Stock_Detail_Service.ArrayOfAnyType parameters) {
            this.parameters = parameters;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStockDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStockDetailsResponse", Namespace="http://tempuri.org/", Order=0)]
        public Bangboo_WS.Stock_Detail_Service.GetStockDetailsResponseBody Body;
        
        public GetStockDetailsResponse() {
        }
        
        public GetStockDetailsResponse(Bangboo_WS.Stock_Detail_Service.GetStockDetailsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStockDetailsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Bangboo_WS.Stock_Detail_Service.VO_Stock_Details[] GetStockDetailsResult;
        
        public GetStockDetailsResponseBody() {
        }
        
        public GetStockDetailsResponseBody(Bangboo_WS.Stock_Detail_Service.VO_Stock_Details[] GetStockDetailsResult) {
            this.GetStockDetailsResult = GetStockDetailsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Stock_Detail_ServiceSoapChannel : Bangboo_WS.Stock_Detail_Service.Stock_Detail_ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Stock_Detail_ServiceSoapClient : System.ServiceModel.ClientBase<Bangboo_WS.Stock_Detail_Service.Stock_Detail_ServiceSoap>, Bangboo_WS.Stock_Detail_Service.Stock_Detail_ServiceSoap {
        
        public Stock_Detail_ServiceSoapClient() {
        }
        
        public Stock_Detail_ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Stock_Detail_ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Stock_Detail_ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Stock_Detail_ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bangboo_WS.Stock_Detail_Service.GetStockDetailsResponse Bangboo_WS.Stock_Detail_Service.Stock_Detail_ServiceSoap.GetStockDetails(Bangboo_WS.Stock_Detail_Service.GetStockDetailsRequest request) {
            return base.Channel.GetStockDetails(request);
        }
        
        public Bangboo_WS.Stock_Detail_Service.VO_Stock_Details[] GetStockDetails(Bangboo_WS.Stock_Detail_Service.ArrayOfAnyType parameters) {
            Bangboo_WS.Stock_Detail_Service.GetStockDetailsRequest inValue = new Bangboo_WS.Stock_Detail_Service.GetStockDetailsRequest();
            inValue.Body = new Bangboo_WS.Stock_Detail_Service.GetStockDetailsRequestBody();
            inValue.Body.parameters = parameters;
            Bangboo_WS.Stock_Detail_Service.GetStockDetailsResponse retVal = ((Bangboo_WS.Stock_Detail_Service.Stock_Detail_ServiceSoap)(this)).GetStockDetails(inValue);
            return retVal.Body.GetStockDetailsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Bangboo_WS.Stock_Detail_Service.GetStockDetailsResponse> Bangboo_WS.Stock_Detail_Service.Stock_Detail_ServiceSoap.GetStockDetailsAsync(Bangboo_WS.Stock_Detail_Service.GetStockDetailsRequest request) {
            return base.Channel.GetStockDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Bangboo_WS.Stock_Detail_Service.GetStockDetailsResponse> GetStockDetailsAsync(Bangboo_WS.Stock_Detail_Service.ArrayOfAnyType parameters) {
            Bangboo_WS.Stock_Detail_Service.GetStockDetailsRequest inValue = new Bangboo_WS.Stock_Detail_Service.GetStockDetailsRequest();
            inValue.Body = new Bangboo_WS.Stock_Detail_Service.GetStockDetailsRequestBody();
            inValue.Body.parameters = parameters;
            return ((Bangboo_WS.Stock_Detail_Service.Stock_Detail_ServiceSoap)(this)).GetStockDetailsAsync(inValue);
        }
    }
}
