//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bangboo_WS.Address_Service {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VO_Addresses", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class VO_Addresses : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ID_AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Street_NumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZipCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID_Address {
            get {
                return this.ID_AddressField;
            }
            set {
                if ((this.ID_AddressField.Equals(value) != true)) {
                    this.ID_AddressField = value;
                    this.RaisePropertyChanged("ID_Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Street_Number {
            get {
                return this.Street_NumberField;
            }
            set {
                if ((object.ReferenceEquals(this.Street_NumberField, value) != true)) {
                    this.Street_NumberField = value;
                    this.RaisePropertyChanged("Street_Number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ZipCode {
            get {
                return this.ZipCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ZipCodeField, value) != true)) {
                    this.ZipCodeField = value;
                    this.RaisePropertyChanged("ZipCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfAnyType", Namespace="http://tempuri.org/", ItemName="anyType")]
    [System.SerializableAttribute()]
    public class ArrayOfAnyType : System.Collections.Generic.List<object> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KeyValuePairOfInt32String", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class KeyValuePairOfInt32String : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Address_Service.Address_ServiceSoap")]
    public interface Address_ServiceSoap {
        
        // CODEGEN: Generating message contract since element name address from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateAddress", ReplyAction="*")]
        Bangboo_WS.Address_Service.CreateAddressResponse CreateAddress(Bangboo_WS.Address_Service.CreateAddressRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateAddress", ReplyAction="*")]
        System.Threading.Tasks.Task<Bangboo_WS.Address_Service.CreateAddressResponse> CreateAddressAsync(Bangboo_WS.Address_Service.CreateAddressRequest request);
        
        // CODEGEN: Generating message contract since element name parameters from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAddresses", ReplyAction="*")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Bangboo_WS.Address_Service.VO_Addresses))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Bangboo_WS.Address_Service.ArrayOfAnyType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Bangboo_WS.Address_Service.VO_Addresses[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Bangboo_WS.Address_Service.KeyValuePairOfInt32String))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Bangboo_WS.Address_Service.KeyValuePairOfInt32String[]))]
        Bangboo_WS.Address_Service.GetAddressesResponse GetAddresses(Bangboo_WS.Address_Service.GetAddressesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAddresses", ReplyAction="*")]
        System.Threading.Tasks.Task<Bangboo_WS.Address_Service.GetAddressesResponse> GetAddressesAsync(Bangboo_WS.Address_Service.GetAddressesRequest request);
        
        // CODEGEN: Generating message contract since element name parameters from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFullAddresses", ReplyAction="*")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Bangboo_WS.Address_Service.VO_Addresses))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Bangboo_WS.Address_Service.ArrayOfAnyType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Bangboo_WS.Address_Service.VO_Addresses[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Bangboo_WS.Address_Service.KeyValuePairOfInt32String))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Bangboo_WS.Address_Service.KeyValuePairOfInt32String[]))]
        Bangboo_WS.Address_Service.GetFullAddressesResponse GetFullAddresses(Bangboo_WS.Address_Service.GetFullAddressesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFullAddresses", ReplyAction="*")]
        System.Threading.Tasks.Task<Bangboo_WS.Address_Service.GetFullAddressesResponse> GetFullAddressesAsync(Bangboo_WS.Address_Service.GetFullAddressesRequest request);
        
        // CODEGEN: Generating message contract since element name address from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateAddress", ReplyAction="*")]
        Bangboo_WS.Address_Service.UpdateAddressResponse UpdateAddress(Bangboo_WS.Address_Service.UpdateAddressRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateAddress", ReplyAction="*")]
        System.Threading.Tasks.Task<Bangboo_WS.Address_Service.UpdateAddressResponse> UpdateAddressAsync(Bangboo_WS.Address_Service.UpdateAddressRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateAddressRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateAddress", Namespace="http://tempuri.org/", Order=0)]
        public Bangboo_WS.Address_Service.CreateAddressRequestBody Body;
        
        public CreateAddressRequest() {
        }
        
        public CreateAddressRequest(Bangboo_WS.Address_Service.CreateAddressRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateAddressRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Bangboo_WS.Address_Service.VO_Addresses address;
        
        public CreateAddressRequestBody() {
        }
        
        public CreateAddressRequestBody(Bangboo_WS.Address_Service.VO_Addresses address) {
            this.address = address;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateAddressResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateAddressResponse", Namespace="http://tempuri.org/", Order=0)]
        public Bangboo_WS.Address_Service.CreateAddressResponseBody Body;
        
        public CreateAddressResponse() {
        }
        
        public CreateAddressResponse(Bangboo_WS.Address_Service.CreateAddressResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateAddressResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CreateAddressResult;
        
        public CreateAddressResponseBody() {
        }
        
        public CreateAddressResponseBody(string CreateAddressResult) {
            this.CreateAddressResult = CreateAddressResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAddressesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAddresses", Namespace="http://tempuri.org/", Order=0)]
        public Bangboo_WS.Address_Service.GetAddressesRequestBody Body;
        
        public GetAddressesRequest() {
        }
        
        public GetAddressesRequest(Bangboo_WS.Address_Service.GetAddressesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAddressesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Bangboo_WS.Address_Service.ArrayOfAnyType parameters;
        
        public GetAddressesRequestBody() {
        }
        
        public GetAddressesRequestBody(Bangboo_WS.Address_Service.ArrayOfAnyType parameters) {
            this.parameters = parameters;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAddressesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAddressesResponse", Namespace="http://tempuri.org/", Order=0)]
        public Bangboo_WS.Address_Service.GetAddressesResponseBody Body;
        
        public GetAddressesResponse() {
        }
        
        public GetAddressesResponse(Bangboo_WS.Address_Service.GetAddressesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAddressesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Bangboo_WS.Address_Service.VO_Addresses[] GetAddressesResult;
        
        public GetAddressesResponseBody() {
        }
        
        public GetAddressesResponseBody(Bangboo_WS.Address_Service.VO_Addresses[] GetAddressesResult) {
            this.GetAddressesResult = GetAddressesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFullAddressesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFullAddresses", Namespace="http://tempuri.org/", Order=0)]
        public Bangboo_WS.Address_Service.GetFullAddressesRequestBody Body;
        
        public GetFullAddressesRequest() {
        }
        
        public GetFullAddressesRequest(Bangboo_WS.Address_Service.GetFullAddressesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFullAddressesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Bangboo_WS.Address_Service.ArrayOfAnyType parameters;
        
        public GetFullAddressesRequestBody() {
        }
        
        public GetFullAddressesRequestBody(Bangboo_WS.Address_Service.ArrayOfAnyType parameters) {
            this.parameters = parameters;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFullAddressesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFullAddressesResponse", Namespace="http://tempuri.org/", Order=0)]
        public Bangboo_WS.Address_Service.GetFullAddressesResponseBody Body;
        
        public GetFullAddressesResponse() {
        }
        
        public GetFullAddressesResponse(Bangboo_WS.Address_Service.GetFullAddressesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFullAddressesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Bangboo_WS.Address_Service.KeyValuePairOfInt32String[] GetFullAddressesResult;
        
        public GetFullAddressesResponseBody() {
        }
        
        public GetFullAddressesResponseBody(Bangboo_WS.Address_Service.KeyValuePairOfInt32String[] GetFullAddressesResult) {
            this.GetFullAddressesResult = GetFullAddressesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateAddressRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateAddress", Namespace="http://tempuri.org/", Order=0)]
        public Bangboo_WS.Address_Service.UpdateAddressRequestBody Body;
        
        public UpdateAddressRequest() {
        }
        
        public UpdateAddressRequest(Bangboo_WS.Address_Service.UpdateAddressRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateAddressRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Bangboo_WS.Address_Service.VO_Addresses address;
        
        public UpdateAddressRequestBody() {
        }
        
        public UpdateAddressRequestBody(Bangboo_WS.Address_Service.VO_Addresses address) {
            this.address = address;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateAddressResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateAddressResponse", Namespace="http://tempuri.org/", Order=0)]
        public Bangboo_WS.Address_Service.UpdateAddressResponseBody Body;
        
        public UpdateAddressResponse() {
        }
        
        public UpdateAddressResponse(Bangboo_WS.Address_Service.UpdateAddressResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateAddressResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpdateAddressResult;
        
        public UpdateAddressResponseBody() {
        }
        
        public UpdateAddressResponseBody(string UpdateAddressResult) {
            this.UpdateAddressResult = UpdateAddressResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Address_ServiceSoapChannel : Bangboo_WS.Address_Service.Address_ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Address_ServiceSoapClient : System.ServiceModel.ClientBase<Bangboo_WS.Address_Service.Address_ServiceSoap>, Bangboo_WS.Address_Service.Address_ServiceSoap {
        
        public Address_ServiceSoapClient() {
        }
        
        public Address_ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Address_ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Address_ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Address_ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bangboo_WS.Address_Service.CreateAddressResponse Bangboo_WS.Address_Service.Address_ServiceSoap.CreateAddress(Bangboo_WS.Address_Service.CreateAddressRequest request) {
            return base.Channel.CreateAddress(request);
        }
        
        public string CreateAddress(Bangboo_WS.Address_Service.VO_Addresses address) {
            Bangboo_WS.Address_Service.CreateAddressRequest inValue = new Bangboo_WS.Address_Service.CreateAddressRequest();
            inValue.Body = new Bangboo_WS.Address_Service.CreateAddressRequestBody();
            inValue.Body.address = address;
            Bangboo_WS.Address_Service.CreateAddressResponse retVal = ((Bangboo_WS.Address_Service.Address_ServiceSoap)(this)).CreateAddress(inValue);
            return retVal.Body.CreateAddressResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Bangboo_WS.Address_Service.CreateAddressResponse> Bangboo_WS.Address_Service.Address_ServiceSoap.CreateAddressAsync(Bangboo_WS.Address_Service.CreateAddressRequest request) {
            return base.Channel.CreateAddressAsync(request);
        }
        
        public System.Threading.Tasks.Task<Bangboo_WS.Address_Service.CreateAddressResponse> CreateAddressAsync(Bangboo_WS.Address_Service.VO_Addresses address) {
            Bangboo_WS.Address_Service.CreateAddressRequest inValue = new Bangboo_WS.Address_Service.CreateAddressRequest();
            inValue.Body = new Bangboo_WS.Address_Service.CreateAddressRequestBody();
            inValue.Body.address = address;
            return ((Bangboo_WS.Address_Service.Address_ServiceSoap)(this)).CreateAddressAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bangboo_WS.Address_Service.GetAddressesResponse Bangboo_WS.Address_Service.Address_ServiceSoap.GetAddresses(Bangboo_WS.Address_Service.GetAddressesRequest request) {
            return base.Channel.GetAddresses(request);
        }
        
        public Bangboo_WS.Address_Service.VO_Addresses[] GetAddresses(Bangboo_WS.Address_Service.ArrayOfAnyType parameters) {
            Bangboo_WS.Address_Service.GetAddressesRequest inValue = new Bangboo_WS.Address_Service.GetAddressesRequest();
            inValue.Body = new Bangboo_WS.Address_Service.GetAddressesRequestBody();
            inValue.Body.parameters = parameters;
            Bangboo_WS.Address_Service.GetAddressesResponse retVal = ((Bangboo_WS.Address_Service.Address_ServiceSoap)(this)).GetAddresses(inValue);
            return retVal.Body.GetAddressesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Bangboo_WS.Address_Service.GetAddressesResponse> Bangboo_WS.Address_Service.Address_ServiceSoap.GetAddressesAsync(Bangboo_WS.Address_Service.GetAddressesRequest request) {
            return base.Channel.GetAddressesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Bangboo_WS.Address_Service.GetAddressesResponse> GetAddressesAsync(Bangboo_WS.Address_Service.ArrayOfAnyType parameters) {
            Bangboo_WS.Address_Service.GetAddressesRequest inValue = new Bangboo_WS.Address_Service.GetAddressesRequest();
            inValue.Body = new Bangboo_WS.Address_Service.GetAddressesRequestBody();
            inValue.Body.parameters = parameters;
            return ((Bangboo_WS.Address_Service.Address_ServiceSoap)(this)).GetAddressesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bangboo_WS.Address_Service.GetFullAddressesResponse Bangboo_WS.Address_Service.Address_ServiceSoap.GetFullAddresses(Bangboo_WS.Address_Service.GetFullAddressesRequest request) {
            return base.Channel.GetFullAddresses(request);
        }
        
        public Bangboo_WS.Address_Service.KeyValuePairOfInt32String[] GetFullAddresses(Bangboo_WS.Address_Service.ArrayOfAnyType parameters) {
            Bangboo_WS.Address_Service.GetFullAddressesRequest inValue = new Bangboo_WS.Address_Service.GetFullAddressesRequest();
            inValue.Body = new Bangboo_WS.Address_Service.GetFullAddressesRequestBody();
            inValue.Body.parameters = parameters;
            Bangboo_WS.Address_Service.GetFullAddressesResponse retVal = ((Bangboo_WS.Address_Service.Address_ServiceSoap)(this)).GetFullAddresses(inValue);
            return retVal.Body.GetFullAddressesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Bangboo_WS.Address_Service.GetFullAddressesResponse> Bangboo_WS.Address_Service.Address_ServiceSoap.GetFullAddressesAsync(Bangboo_WS.Address_Service.GetFullAddressesRequest request) {
            return base.Channel.GetFullAddressesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Bangboo_WS.Address_Service.GetFullAddressesResponse> GetFullAddressesAsync(Bangboo_WS.Address_Service.ArrayOfAnyType parameters) {
            Bangboo_WS.Address_Service.GetFullAddressesRequest inValue = new Bangboo_WS.Address_Service.GetFullAddressesRequest();
            inValue.Body = new Bangboo_WS.Address_Service.GetFullAddressesRequestBody();
            inValue.Body.parameters = parameters;
            return ((Bangboo_WS.Address_Service.Address_ServiceSoap)(this)).GetFullAddressesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bangboo_WS.Address_Service.UpdateAddressResponse Bangboo_WS.Address_Service.Address_ServiceSoap.UpdateAddress(Bangboo_WS.Address_Service.UpdateAddressRequest request) {
            return base.Channel.UpdateAddress(request);
        }
        
        public string UpdateAddress(Bangboo_WS.Address_Service.VO_Addresses address) {
            Bangboo_WS.Address_Service.UpdateAddressRequest inValue = new Bangboo_WS.Address_Service.UpdateAddressRequest();
            inValue.Body = new Bangboo_WS.Address_Service.UpdateAddressRequestBody();
            inValue.Body.address = address;
            Bangboo_WS.Address_Service.UpdateAddressResponse retVal = ((Bangboo_WS.Address_Service.Address_ServiceSoap)(this)).UpdateAddress(inValue);
            return retVal.Body.UpdateAddressResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Bangboo_WS.Address_Service.UpdateAddressResponse> Bangboo_WS.Address_Service.Address_ServiceSoap.UpdateAddressAsync(Bangboo_WS.Address_Service.UpdateAddressRequest request) {
            return base.Channel.UpdateAddressAsync(request);
        }
        
        public System.Threading.Tasks.Task<Bangboo_WS.Address_Service.UpdateAddressResponse> UpdateAddressAsync(Bangboo_WS.Address_Service.VO_Addresses address) {
            Bangboo_WS.Address_Service.UpdateAddressRequest inValue = new Bangboo_WS.Address_Service.UpdateAddressRequest();
            inValue.Body = new Bangboo_WS.Address_Service.UpdateAddressRequestBody();
            inValue.Body.address = address;
            return ((Bangboo_WS.Address_Service.Address_ServiceSoap)(this)).UpdateAddressAsync(inValue);
        }
    }
}
