//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bangboo_WS.BangbooSale_Service {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VO_BangbooSales", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class VO_BangbooSales : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int Bangboo_IDField;
        
        private int SalesReceipt_IDField;
        
        private int QuantityField;
        
        private int ID_BangbooSalesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Bangboo_ID {
            get {
                return this.Bangboo_IDField;
            }
            set {
                if ((this.Bangboo_IDField.Equals(value) != true)) {
                    this.Bangboo_IDField = value;
                    this.RaisePropertyChanged("Bangboo_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int SalesReceipt_ID {
            get {
                return this.SalesReceipt_IDField;
            }
            set {
                if ((this.SalesReceipt_IDField.Equals(value) != true)) {
                    this.SalesReceipt_IDField = value;
                    this.RaisePropertyChanged("SalesReceipt_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int ID_BangbooSales {
            get {
                return this.ID_BangbooSalesField;
            }
            set {
                if ((this.ID_BangbooSalesField.Equals(value) != true)) {
                    this.ID_BangbooSalesField = value;
                    this.RaisePropertyChanged("ID_BangbooSales");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfAnyType", Namespace="http://tempuri.org/", ItemName="anyType")]
    [System.SerializableAttribute()]
    public class ArrayOfAnyType : System.Collections.Generic.List<object> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BangbooSale_Service.BangbooSale_ServiceSoap")]
    public interface BangbooSale_ServiceSoap {
        
        // CODEGEN: Generating message contract since element name bangboo_sale from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateBangbooSale", ReplyAction="*")]
        Bangboo_WS.BangbooSale_Service.CreateBangbooSaleResponse CreateBangbooSale(Bangboo_WS.BangbooSale_Service.CreateBangbooSaleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateBangbooSale", ReplyAction="*")]
        System.Threading.Tasks.Task<Bangboo_WS.BangbooSale_Service.CreateBangbooSaleResponse> CreateBangbooSaleAsync(Bangboo_WS.BangbooSale_Service.CreateBangbooSaleRequest request);
        
        // CODEGEN: Generating message contract since element name parameters from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBangbooSales", ReplyAction="*")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Bangboo_WS.BangbooSale_Service.VO_BangbooSales))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Bangboo_WS.BangbooSale_Service.ArrayOfAnyType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Bangboo_WS.BangbooSale_Service.VO_BangbooSales[]))]
        Bangboo_WS.BangbooSale_Service.GetBangbooSalesResponse GetBangbooSales(Bangboo_WS.BangbooSale_Service.GetBangbooSalesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBangbooSales", ReplyAction="*")]
        System.Threading.Tasks.Task<Bangboo_WS.BangbooSale_Service.GetBangbooSalesResponse> GetBangbooSalesAsync(Bangboo_WS.BangbooSale_Service.GetBangbooSalesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateBangbooSaleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateBangbooSale", Namespace="http://tempuri.org/", Order=0)]
        public Bangboo_WS.BangbooSale_Service.CreateBangbooSaleRequestBody Body;
        
        public CreateBangbooSaleRequest() {
        }
        
        public CreateBangbooSaleRequest(Bangboo_WS.BangbooSale_Service.CreateBangbooSaleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateBangbooSaleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Bangboo_WS.BangbooSale_Service.VO_BangbooSales bangboo_sale;
        
        public CreateBangbooSaleRequestBody() {
        }
        
        public CreateBangbooSaleRequestBody(Bangboo_WS.BangbooSale_Service.VO_BangbooSales bangboo_sale) {
            this.bangboo_sale = bangboo_sale;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateBangbooSaleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateBangbooSaleResponse", Namespace="http://tempuri.org/", Order=0)]
        public Bangboo_WS.BangbooSale_Service.CreateBangbooSaleResponseBody Body;
        
        public CreateBangbooSaleResponse() {
        }
        
        public CreateBangbooSaleResponse(Bangboo_WS.BangbooSale_Service.CreateBangbooSaleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateBangbooSaleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CreateBangbooSaleResult;
        
        public CreateBangbooSaleResponseBody() {
        }
        
        public CreateBangbooSaleResponseBody(string CreateBangbooSaleResult) {
            this.CreateBangbooSaleResult = CreateBangbooSaleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBangbooSalesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBangbooSales", Namespace="http://tempuri.org/", Order=0)]
        public Bangboo_WS.BangbooSale_Service.GetBangbooSalesRequestBody Body;
        
        public GetBangbooSalesRequest() {
        }
        
        public GetBangbooSalesRequest(Bangboo_WS.BangbooSale_Service.GetBangbooSalesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBangbooSalesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Bangboo_WS.BangbooSale_Service.ArrayOfAnyType parameters;
        
        public GetBangbooSalesRequestBody() {
        }
        
        public GetBangbooSalesRequestBody(Bangboo_WS.BangbooSale_Service.ArrayOfAnyType parameters) {
            this.parameters = parameters;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBangbooSalesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBangbooSalesResponse", Namespace="http://tempuri.org/", Order=0)]
        public Bangboo_WS.BangbooSale_Service.GetBangbooSalesResponseBody Body;
        
        public GetBangbooSalesResponse() {
        }
        
        public GetBangbooSalesResponse(Bangboo_WS.BangbooSale_Service.GetBangbooSalesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBangbooSalesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Bangboo_WS.BangbooSale_Service.VO_BangbooSales[] GetBangbooSalesResult;
        
        public GetBangbooSalesResponseBody() {
        }
        
        public GetBangbooSalesResponseBody(Bangboo_WS.BangbooSale_Service.VO_BangbooSales[] GetBangbooSalesResult) {
            this.GetBangbooSalesResult = GetBangbooSalesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BangbooSale_ServiceSoapChannel : Bangboo_WS.BangbooSale_Service.BangbooSale_ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BangbooSale_ServiceSoapClient : System.ServiceModel.ClientBase<Bangboo_WS.BangbooSale_Service.BangbooSale_ServiceSoap>, Bangboo_WS.BangbooSale_Service.BangbooSale_ServiceSoap {
        
        public BangbooSale_ServiceSoapClient() {
        }
        
        public BangbooSale_ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BangbooSale_ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BangbooSale_ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BangbooSale_ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bangboo_WS.BangbooSale_Service.CreateBangbooSaleResponse Bangboo_WS.BangbooSale_Service.BangbooSale_ServiceSoap.CreateBangbooSale(Bangboo_WS.BangbooSale_Service.CreateBangbooSaleRequest request) {
            return base.Channel.CreateBangbooSale(request);
        }
        
        public string CreateBangbooSale(Bangboo_WS.BangbooSale_Service.VO_BangbooSales bangboo_sale) {
            Bangboo_WS.BangbooSale_Service.CreateBangbooSaleRequest inValue = new Bangboo_WS.BangbooSale_Service.CreateBangbooSaleRequest();
            inValue.Body = new Bangboo_WS.BangbooSale_Service.CreateBangbooSaleRequestBody();
            inValue.Body.bangboo_sale = bangboo_sale;
            Bangboo_WS.BangbooSale_Service.CreateBangbooSaleResponse retVal = ((Bangboo_WS.BangbooSale_Service.BangbooSale_ServiceSoap)(this)).CreateBangbooSale(inValue);
            return retVal.Body.CreateBangbooSaleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Bangboo_WS.BangbooSale_Service.CreateBangbooSaleResponse> Bangboo_WS.BangbooSale_Service.BangbooSale_ServiceSoap.CreateBangbooSaleAsync(Bangboo_WS.BangbooSale_Service.CreateBangbooSaleRequest request) {
            return base.Channel.CreateBangbooSaleAsync(request);
        }
        
        public System.Threading.Tasks.Task<Bangboo_WS.BangbooSale_Service.CreateBangbooSaleResponse> CreateBangbooSaleAsync(Bangboo_WS.BangbooSale_Service.VO_BangbooSales bangboo_sale) {
            Bangboo_WS.BangbooSale_Service.CreateBangbooSaleRequest inValue = new Bangboo_WS.BangbooSale_Service.CreateBangbooSaleRequest();
            inValue.Body = new Bangboo_WS.BangbooSale_Service.CreateBangbooSaleRequestBody();
            inValue.Body.bangboo_sale = bangboo_sale;
            return ((Bangboo_WS.BangbooSale_Service.BangbooSale_ServiceSoap)(this)).CreateBangbooSaleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bangboo_WS.BangbooSale_Service.GetBangbooSalesResponse Bangboo_WS.BangbooSale_Service.BangbooSale_ServiceSoap.GetBangbooSales(Bangboo_WS.BangbooSale_Service.GetBangbooSalesRequest request) {
            return base.Channel.GetBangbooSales(request);
        }
        
        public Bangboo_WS.BangbooSale_Service.VO_BangbooSales[] GetBangbooSales(Bangboo_WS.BangbooSale_Service.ArrayOfAnyType parameters) {
            Bangboo_WS.BangbooSale_Service.GetBangbooSalesRequest inValue = new Bangboo_WS.BangbooSale_Service.GetBangbooSalesRequest();
            inValue.Body = new Bangboo_WS.BangbooSale_Service.GetBangbooSalesRequestBody();
            inValue.Body.parameters = parameters;
            Bangboo_WS.BangbooSale_Service.GetBangbooSalesResponse retVal = ((Bangboo_WS.BangbooSale_Service.BangbooSale_ServiceSoap)(this)).GetBangbooSales(inValue);
            return retVal.Body.GetBangbooSalesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Bangboo_WS.BangbooSale_Service.GetBangbooSalesResponse> Bangboo_WS.BangbooSale_Service.BangbooSale_ServiceSoap.GetBangbooSalesAsync(Bangboo_WS.BangbooSale_Service.GetBangbooSalesRequest request) {
            return base.Channel.GetBangbooSalesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Bangboo_WS.BangbooSale_Service.GetBangbooSalesResponse> GetBangbooSalesAsync(Bangboo_WS.BangbooSale_Service.ArrayOfAnyType parameters) {
            Bangboo_WS.BangbooSale_Service.GetBangbooSalesRequest inValue = new Bangboo_WS.BangbooSale_Service.GetBangbooSalesRequest();
            inValue.Body = new Bangboo_WS.BangbooSale_Service.GetBangbooSalesRequestBody();
            inValue.Body.parameters = parameters;
            return ((Bangboo_WS.BangbooSale_Service.BangbooSale_ServiceSoap)(this)).GetBangbooSalesAsync(inValue);
        }
    }
}
