//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bangboo_WS.Employee_Service {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VO_Employees", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class VO_Employees : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ID_EmployeeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HireDateField;
        
        private float SalaryField;
        
        private int Address_IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID_Employee {
            get {
                return this.ID_EmployeeField;
            }
            set {
                if ((this.ID_EmployeeField.Equals(value) != true)) {
                    this.ID_EmployeeField = value;
                    this.RaisePropertyChanged("ID_Employee");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string HireDate {
            get {
                return this.HireDateField;
            }
            set {
                if ((object.ReferenceEquals(this.HireDateField, value) != true)) {
                    this.HireDateField = value;
                    this.RaisePropertyChanged("HireDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public float Salary {
            get {
                return this.SalaryField;
            }
            set {
                if ((this.SalaryField.Equals(value) != true)) {
                    this.SalaryField = value;
                    this.RaisePropertyChanged("Salary");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int Address_ID {
            get {
                return this.Address_IDField;
            }
            set {
                if ((this.Address_IDField.Equals(value) != true)) {
                    this.Address_IDField = value;
                    this.RaisePropertyChanged("Address_ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfAnyType", Namespace="http://tempuri.org/", ItemName="anyType")]
    [System.SerializableAttribute()]
    public class ArrayOfAnyType : System.Collections.Generic.List<object> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KeyValuePairOfInt32String", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class KeyValuePairOfInt32String : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Employee_Service.Employee_ServiceSoap")]
    public interface Employee_ServiceSoap {
        
        // CODEGEN: Generating message contract since element name employee from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateEmployee", ReplyAction="*")]
        Bangboo_WS.Employee_Service.CreateEmployeeResponse CreateEmployee(Bangboo_WS.Employee_Service.CreateEmployeeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateEmployee", ReplyAction="*")]
        System.Threading.Tasks.Task<Bangboo_WS.Employee_Service.CreateEmployeeResponse> CreateEmployeeAsync(Bangboo_WS.Employee_Service.CreateEmployeeRequest request);
        
        // CODEGEN: Generating message contract since element name parameters from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEmployees", ReplyAction="*")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Bangboo_WS.Employee_Service.VO_Employees))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Bangboo_WS.Employee_Service.ArrayOfAnyType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Bangboo_WS.Employee_Service.VO_Employees[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Bangboo_WS.Employee_Service.KeyValuePairOfInt32String))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Bangboo_WS.Employee_Service.KeyValuePairOfInt32String[]))]
        Bangboo_WS.Employee_Service.GetEmployeesResponse GetEmployees(Bangboo_WS.Employee_Service.GetEmployeesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEmployees", ReplyAction="*")]
        System.Threading.Tasks.Task<Bangboo_WS.Employee_Service.GetEmployeesResponse> GetEmployeesAsync(Bangboo_WS.Employee_Service.GetEmployeesRequest request);
        
        // CODEGEN: Generating message contract since element name parameters from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEmployeeNames", ReplyAction="*")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Bangboo_WS.Employee_Service.VO_Employees))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Bangboo_WS.Employee_Service.ArrayOfAnyType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Bangboo_WS.Employee_Service.VO_Employees[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Bangboo_WS.Employee_Service.KeyValuePairOfInt32String))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Bangboo_WS.Employee_Service.KeyValuePairOfInt32String[]))]
        Bangboo_WS.Employee_Service.GetEmployeeNamesResponse GetEmployeeNames(Bangboo_WS.Employee_Service.GetEmployeeNamesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEmployeeNames", ReplyAction="*")]
        System.Threading.Tasks.Task<Bangboo_WS.Employee_Service.GetEmployeeNamesResponse> GetEmployeeNamesAsync(Bangboo_WS.Employee_Service.GetEmployeeNamesRequest request);
        
        // CODEGEN: Generating message contract since element name employee from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateEmployee", ReplyAction="*")]
        Bangboo_WS.Employee_Service.UpdateEmployeeResponse UpdateEmployee(Bangboo_WS.Employee_Service.UpdateEmployeeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateEmployee", ReplyAction="*")]
        System.Threading.Tasks.Task<Bangboo_WS.Employee_Service.UpdateEmployeeResponse> UpdateEmployeeAsync(Bangboo_WS.Employee_Service.UpdateEmployeeRequest request);
        
        // CODEGEN: Generating message contract since element name DeleteEmployeeResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteEmployee", ReplyAction="*")]
        Bangboo_WS.Employee_Service.DeleteEmployeeResponse DeleteEmployee(Bangboo_WS.Employee_Service.DeleteEmployeeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteEmployee", ReplyAction="*")]
        System.Threading.Tasks.Task<Bangboo_WS.Employee_Service.DeleteEmployeeResponse> DeleteEmployeeAsync(Bangboo_WS.Employee_Service.DeleteEmployeeRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateEmployeeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateEmployee", Namespace="http://tempuri.org/", Order=0)]
        public Bangboo_WS.Employee_Service.CreateEmployeeRequestBody Body;
        
        public CreateEmployeeRequest() {
        }
        
        public CreateEmployeeRequest(Bangboo_WS.Employee_Service.CreateEmployeeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateEmployeeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Bangboo_WS.Employee_Service.VO_Employees employee;
        
        public CreateEmployeeRequestBody() {
        }
        
        public CreateEmployeeRequestBody(Bangboo_WS.Employee_Service.VO_Employees employee) {
            this.employee = employee;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateEmployeeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateEmployeeResponse", Namespace="http://tempuri.org/", Order=0)]
        public Bangboo_WS.Employee_Service.CreateEmployeeResponseBody Body;
        
        public CreateEmployeeResponse() {
        }
        
        public CreateEmployeeResponse(Bangboo_WS.Employee_Service.CreateEmployeeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateEmployeeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CreateEmployeeResult;
        
        public CreateEmployeeResponseBody() {
        }
        
        public CreateEmployeeResponseBody(string CreateEmployeeResult) {
            this.CreateEmployeeResult = CreateEmployeeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEmployeesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEmployees", Namespace="http://tempuri.org/", Order=0)]
        public Bangboo_WS.Employee_Service.GetEmployeesRequestBody Body;
        
        public GetEmployeesRequest() {
        }
        
        public GetEmployeesRequest(Bangboo_WS.Employee_Service.GetEmployeesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetEmployeesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Bangboo_WS.Employee_Service.ArrayOfAnyType parameters;
        
        public GetEmployeesRequestBody() {
        }
        
        public GetEmployeesRequestBody(Bangboo_WS.Employee_Service.ArrayOfAnyType parameters) {
            this.parameters = parameters;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEmployeesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEmployeesResponse", Namespace="http://tempuri.org/", Order=0)]
        public Bangboo_WS.Employee_Service.GetEmployeesResponseBody Body;
        
        public GetEmployeesResponse() {
        }
        
        public GetEmployeesResponse(Bangboo_WS.Employee_Service.GetEmployeesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetEmployeesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Bangboo_WS.Employee_Service.VO_Employees[] GetEmployeesResult;
        
        public GetEmployeesResponseBody() {
        }
        
        public GetEmployeesResponseBody(Bangboo_WS.Employee_Service.VO_Employees[] GetEmployeesResult) {
            this.GetEmployeesResult = GetEmployeesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEmployeeNamesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEmployeeNames", Namespace="http://tempuri.org/", Order=0)]
        public Bangboo_WS.Employee_Service.GetEmployeeNamesRequestBody Body;
        
        public GetEmployeeNamesRequest() {
        }
        
        public GetEmployeeNamesRequest(Bangboo_WS.Employee_Service.GetEmployeeNamesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetEmployeeNamesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Bangboo_WS.Employee_Service.ArrayOfAnyType parameters;
        
        public GetEmployeeNamesRequestBody() {
        }
        
        public GetEmployeeNamesRequestBody(Bangboo_WS.Employee_Service.ArrayOfAnyType parameters) {
            this.parameters = parameters;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEmployeeNamesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEmployeeNamesResponse", Namespace="http://tempuri.org/", Order=0)]
        public Bangboo_WS.Employee_Service.GetEmployeeNamesResponseBody Body;
        
        public GetEmployeeNamesResponse() {
        }
        
        public GetEmployeeNamesResponse(Bangboo_WS.Employee_Service.GetEmployeeNamesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetEmployeeNamesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Bangboo_WS.Employee_Service.KeyValuePairOfInt32String[] GetEmployeeNamesResult;
        
        public GetEmployeeNamesResponseBody() {
        }
        
        public GetEmployeeNamesResponseBody(Bangboo_WS.Employee_Service.KeyValuePairOfInt32String[] GetEmployeeNamesResult) {
            this.GetEmployeeNamesResult = GetEmployeeNamesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateEmployeeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateEmployee", Namespace="http://tempuri.org/", Order=0)]
        public Bangboo_WS.Employee_Service.UpdateEmployeeRequestBody Body;
        
        public UpdateEmployeeRequest() {
        }
        
        public UpdateEmployeeRequest(Bangboo_WS.Employee_Service.UpdateEmployeeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateEmployeeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Bangboo_WS.Employee_Service.VO_Employees employee;
        
        public UpdateEmployeeRequestBody() {
        }
        
        public UpdateEmployeeRequestBody(Bangboo_WS.Employee_Service.VO_Employees employee) {
            this.employee = employee;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateEmployeeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateEmployeeResponse", Namespace="http://tempuri.org/", Order=0)]
        public Bangboo_WS.Employee_Service.UpdateEmployeeResponseBody Body;
        
        public UpdateEmployeeResponse() {
        }
        
        public UpdateEmployeeResponse(Bangboo_WS.Employee_Service.UpdateEmployeeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateEmployeeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpdateEmployeeResult;
        
        public UpdateEmployeeResponseBody() {
        }
        
        public UpdateEmployeeResponseBody(string UpdateEmployeeResult) {
            this.UpdateEmployeeResult = UpdateEmployeeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteEmployeeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteEmployee", Namespace="http://tempuri.org/", Order=0)]
        public Bangboo_WS.Employee_Service.DeleteEmployeeRequestBody Body;
        
        public DeleteEmployeeRequest() {
        }
        
        public DeleteEmployeeRequest(Bangboo_WS.Employee_Service.DeleteEmployeeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteEmployeeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public DeleteEmployeeRequestBody() {
        }
        
        public DeleteEmployeeRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteEmployeeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteEmployeeResponse", Namespace="http://tempuri.org/", Order=0)]
        public Bangboo_WS.Employee_Service.DeleteEmployeeResponseBody Body;
        
        public DeleteEmployeeResponse() {
        }
        
        public DeleteEmployeeResponse(Bangboo_WS.Employee_Service.DeleteEmployeeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteEmployeeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DeleteEmployeeResult;
        
        public DeleteEmployeeResponseBody() {
        }
        
        public DeleteEmployeeResponseBody(string DeleteEmployeeResult) {
            this.DeleteEmployeeResult = DeleteEmployeeResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Employee_ServiceSoapChannel : Bangboo_WS.Employee_Service.Employee_ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Employee_ServiceSoapClient : System.ServiceModel.ClientBase<Bangboo_WS.Employee_Service.Employee_ServiceSoap>, Bangboo_WS.Employee_Service.Employee_ServiceSoap {
        
        public Employee_ServiceSoapClient() {
        }
        
        public Employee_ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Employee_ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Employee_ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Employee_ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bangboo_WS.Employee_Service.CreateEmployeeResponse Bangboo_WS.Employee_Service.Employee_ServiceSoap.CreateEmployee(Bangboo_WS.Employee_Service.CreateEmployeeRequest request) {
            return base.Channel.CreateEmployee(request);
        }
        
        public string CreateEmployee(Bangboo_WS.Employee_Service.VO_Employees employee) {
            Bangboo_WS.Employee_Service.CreateEmployeeRequest inValue = new Bangboo_WS.Employee_Service.CreateEmployeeRequest();
            inValue.Body = new Bangboo_WS.Employee_Service.CreateEmployeeRequestBody();
            inValue.Body.employee = employee;
            Bangboo_WS.Employee_Service.CreateEmployeeResponse retVal = ((Bangboo_WS.Employee_Service.Employee_ServiceSoap)(this)).CreateEmployee(inValue);
            return retVal.Body.CreateEmployeeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Bangboo_WS.Employee_Service.CreateEmployeeResponse> Bangboo_WS.Employee_Service.Employee_ServiceSoap.CreateEmployeeAsync(Bangboo_WS.Employee_Service.CreateEmployeeRequest request) {
            return base.Channel.CreateEmployeeAsync(request);
        }
        
        public System.Threading.Tasks.Task<Bangboo_WS.Employee_Service.CreateEmployeeResponse> CreateEmployeeAsync(Bangboo_WS.Employee_Service.VO_Employees employee) {
            Bangboo_WS.Employee_Service.CreateEmployeeRequest inValue = new Bangboo_WS.Employee_Service.CreateEmployeeRequest();
            inValue.Body = new Bangboo_WS.Employee_Service.CreateEmployeeRequestBody();
            inValue.Body.employee = employee;
            return ((Bangboo_WS.Employee_Service.Employee_ServiceSoap)(this)).CreateEmployeeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bangboo_WS.Employee_Service.GetEmployeesResponse Bangboo_WS.Employee_Service.Employee_ServiceSoap.GetEmployees(Bangboo_WS.Employee_Service.GetEmployeesRequest request) {
            return base.Channel.GetEmployees(request);
        }
        
        public Bangboo_WS.Employee_Service.VO_Employees[] GetEmployees(Bangboo_WS.Employee_Service.ArrayOfAnyType parameters) {
            Bangboo_WS.Employee_Service.GetEmployeesRequest inValue = new Bangboo_WS.Employee_Service.GetEmployeesRequest();
            inValue.Body = new Bangboo_WS.Employee_Service.GetEmployeesRequestBody();
            inValue.Body.parameters = parameters;
            Bangboo_WS.Employee_Service.GetEmployeesResponse retVal = ((Bangboo_WS.Employee_Service.Employee_ServiceSoap)(this)).GetEmployees(inValue);
            return retVal.Body.GetEmployeesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Bangboo_WS.Employee_Service.GetEmployeesResponse> Bangboo_WS.Employee_Service.Employee_ServiceSoap.GetEmployeesAsync(Bangboo_WS.Employee_Service.GetEmployeesRequest request) {
            return base.Channel.GetEmployeesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Bangboo_WS.Employee_Service.GetEmployeesResponse> GetEmployeesAsync(Bangboo_WS.Employee_Service.ArrayOfAnyType parameters) {
            Bangboo_WS.Employee_Service.GetEmployeesRequest inValue = new Bangboo_WS.Employee_Service.GetEmployeesRequest();
            inValue.Body = new Bangboo_WS.Employee_Service.GetEmployeesRequestBody();
            inValue.Body.parameters = parameters;
            return ((Bangboo_WS.Employee_Service.Employee_ServiceSoap)(this)).GetEmployeesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bangboo_WS.Employee_Service.GetEmployeeNamesResponse Bangboo_WS.Employee_Service.Employee_ServiceSoap.GetEmployeeNames(Bangboo_WS.Employee_Service.GetEmployeeNamesRequest request) {
            return base.Channel.GetEmployeeNames(request);
        }
        
        public Bangboo_WS.Employee_Service.KeyValuePairOfInt32String[] GetEmployeeNames(Bangboo_WS.Employee_Service.ArrayOfAnyType parameters) {
            Bangboo_WS.Employee_Service.GetEmployeeNamesRequest inValue = new Bangboo_WS.Employee_Service.GetEmployeeNamesRequest();
            inValue.Body = new Bangboo_WS.Employee_Service.GetEmployeeNamesRequestBody();
            inValue.Body.parameters = parameters;
            Bangboo_WS.Employee_Service.GetEmployeeNamesResponse retVal = ((Bangboo_WS.Employee_Service.Employee_ServiceSoap)(this)).GetEmployeeNames(inValue);
            return retVal.Body.GetEmployeeNamesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Bangboo_WS.Employee_Service.GetEmployeeNamesResponse> Bangboo_WS.Employee_Service.Employee_ServiceSoap.GetEmployeeNamesAsync(Bangboo_WS.Employee_Service.GetEmployeeNamesRequest request) {
            return base.Channel.GetEmployeeNamesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Bangboo_WS.Employee_Service.GetEmployeeNamesResponse> GetEmployeeNamesAsync(Bangboo_WS.Employee_Service.ArrayOfAnyType parameters) {
            Bangboo_WS.Employee_Service.GetEmployeeNamesRequest inValue = new Bangboo_WS.Employee_Service.GetEmployeeNamesRequest();
            inValue.Body = new Bangboo_WS.Employee_Service.GetEmployeeNamesRequestBody();
            inValue.Body.parameters = parameters;
            return ((Bangboo_WS.Employee_Service.Employee_ServiceSoap)(this)).GetEmployeeNamesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bangboo_WS.Employee_Service.UpdateEmployeeResponse Bangboo_WS.Employee_Service.Employee_ServiceSoap.UpdateEmployee(Bangboo_WS.Employee_Service.UpdateEmployeeRequest request) {
            return base.Channel.UpdateEmployee(request);
        }
        
        public string UpdateEmployee(Bangboo_WS.Employee_Service.VO_Employees employee) {
            Bangboo_WS.Employee_Service.UpdateEmployeeRequest inValue = new Bangboo_WS.Employee_Service.UpdateEmployeeRequest();
            inValue.Body = new Bangboo_WS.Employee_Service.UpdateEmployeeRequestBody();
            inValue.Body.employee = employee;
            Bangboo_WS.Employee_Service.UpdateEmployeeResponse retVal = ((Bangboo_WS.Employee_Service.Employee_ServiceSoap)(this)).UpdateEmployee(inValue);
            return retVal.Body.UpdateEmployeeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Bangboo_WS.Employee_Service.UpdateEmployeeResponse> Bangboo_WS.Employee_Service.Employee_ServiceSoap.UpdateEmployeeAsync(Bangboo_WS.Employee_Service.UpdateEmployeeRequest request) {
            return base.Channel.UpdateEmployeeAsync(request);
        }
        
        public System.Threading.Tasks.Task<Bangboo_WS.Employee_Service.UpdateEmployeeResponse> UpdateEmployeeAsync(Bangboo_WS.Employee_Service.VO_Employees employee) {
            Bangboo_WS.Employee_Service.UpdateEmployeeRequest inValue = new Bangboo_WS.Employee_Service.UpdateEmployeeRequest();
            inValue.Body = new Bangboo_WS.Employee_Service.UpdateEmployeeRequestBody();
            inValue.Body.employee = employee;
            return ((Bangboo_WS.Employee_Service.Employee_ServiceSoap)(this)).UpdateEmployeeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bangboo_WS.Employee_Service.DeleteEmployeeResponse Bangboo_WS.Employee_Service.Employee_ServiceSoap.DeleteEmployee(Bangboo_WS.Employee_Service.DeleteEmployeeRequest request) {
            return base.Channel.DeleteEmployee(request);
        }
        
        public string DeleteEmployee(int id) {
            Bangboo_WS.Employee_Service.DeleteEmployeeRequest inValue = new Bangboo_WS.Employee_Service.DeleteEmployeeRequest();
            inValue.Body = new Bangboo_WS.Employee_Service.DeleteEmployeeRequestBody();
            inValue.Body.id = id;
            Bangboo_WS.Employee_Service.DeleteEmployeeResponse retVal = ((Bangboo_WS.Employee_Service.Employee_ServiceSoap)(this)).DeleteEmployee(inValue);
            return retVal.Body.DeleteEmployeeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Bangboo_WS.Employee_Service.DeleteEmployeeResponse> Bangboo_WS.Employee_Service.Employee_ServiceSoap.DeleteEmployeeAsync(Bangboo_WS.Employee_Service.DeleteEmployeeRequest request) {
            return base.Channel.DeleteEmployeeAsync(request);
        }
        
        public System.Threading.Tasks.Task<Bangboo_WS.Employee_Service.DeleteEmployeeResponse> DeleteEmployeeAsync(int id) {
            Bangboo_WS.Employee_Service.DeleteEmployeeRequest inValue = new Bangboo_WS.Employee_Service.DeleteEmployeeRequest();
            inValue.Body = new Bangboo_WS.Employee_Service.DeleteEmployeeRequestBody();
            inValue.Body.id = id;
            return ((Bangboo_WS.Employee_Service.Employee_ServiceSoap)(this)).DeleteEmployeeAsync(inValue);
        }
    }
}
