//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bangboo_WS.BangbooSupplyDetail_Service {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VO_BangbooSupplyDetails", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class VO_BangbooSupplyDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ID_DetailField;
        
        private int ID_BangbooField;
        
        private int ID_SupplierField;
        
        private int SupplyAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SupplyDateField;
        
        private int UnitCostField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID_Detail {
            get {
                return this.ID_DetailField;
            }
            set {
                if ((this.ID_DetailField.Equals(value) != true)) {
                    this.ID_DetailField = value;
                    this.RaisePropertyChanged("ID_Detail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int ID_Bangboo {
            get {
                return this.ID_BangbooField;
            }
            set {
                if ((this.ID_BangbooField.Equals(value) != true)) {
                    this.ID_BangbooField = value;
                    this.RaisePropertyChanged("ID_Bangboo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int ID_Supplier {
            get {
                return this.ID_SupplierField;
            }
            set {
                if ((this.ID_SupplierField.Equals(value) != true)) {
                    this.ID_SupplierField = value;
                    this.RaisePropertyChanged("ID_Supplier");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int SupplyAmount {
            get {
                return this.SupplyAmountField;
            }
            set {
                if ((this.SupplyAmountField.Equals(value) != true)) {
                    this.SupplyAmountField = value;
                    this.RaisePropertyChanged("SupplyAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string SupplyDate {
            get {
                return this.SupplyDateField;
            }
            set {
                if ((object.ReferenceEquals(this.SupplyDateField, value) != true)) {
                    this.SupplyDateField = value;
                    this.RaisePropertyChanged("SupplyDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int UnitCost {
            get {
                return this.UnitCostField;
            }
            set {
                if ((this.UnitCostField.Equals(value) != true)) {
                    this.UnitCostField = value;
                    this.RaisePropertyChanged("UnitCost");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfAnyType", Namespace="http://tempuri.org/", ItemName="anyType")]
    [System.SerializableAttribute()]
    public class ArrayOfAnyType : System.Collections.Generic.List<object> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BangbooSupplyDetail_Service.BangbooSupplyDetail_ServiceSoap")]
    public interface BangbooSupplyDetail_ServiceSoap {
        
        // CODEGEN: Generating message contract since element name detail from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateBangbooSupplyDetail", ReplyAction="*")]
        Bangboo_WS.BangbooSupplyDetail_Service.CreateBangbooSupplyDetailResponse CreateBangbooSupplyDetail(Bangboo_WS.BangbooSupplyDetail_Service.CreateBangbooSupplyDetailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateBangbooSupplyDetail", ReplyAction="*")]
        System.Threading.Tasks.Task<Bangboo_WS.BangbooSupplyDetail_Service.CreateBangbooSupplyDetailResponse> CreateBangbooSupplyDetailAsync(Bangboo_WS.BangbooSupplyDetail_Service.CreateBangbooSupplyDetailRequest request);
        
        // CODEGEN: Generating message contract since element name parameters from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBangbooSupplyDetails", ReplyAction="*")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Bangboo_WS.BangbooSupplyDetail_Service.VO_BangbooSupplyDetails))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Bangboo_WS.BangbooSupplyDetail_Service.ArrayOfAnyType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Bangboo_WS.BangbooSupplyDetail_Service.VO_BangbooSupplyDetails[]))]
        Bangboo_WS.BangbooSupplyDetail_Service.GetBangbooSupplyDetailsResponse GetBangbooSupplyDetails(Bangboo_WS.BangbooSupplyDetail_Service.GetBangbooSupplyDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBangbooSupplyDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<Bangboo_WS.BangbooSupplyDetail_Service.GetBangbooSupplyDetailsResponse> GetBangbooSupplyDetailsAsync(Bangboo_WS.BangbooSupplyDetail_Service.GetBangbooSupplyDetailsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateBangbooSupplyDetailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateBangbooSupplyDetail", Namespace="http://tempuri.org/", Order=0)]
        public Bangboo_WS.BangbooSupplyDetail_Service.CreateBangbooSupplyDetailRequestBody Body;
        
        public CreateBangbooSupplyDetailRequest() {
        }
        
        public CreateBangbooSupplyDetailRequest(Bangboo_WS.BangbooSupplyDetail_Service.CreateBangbooSupplyDetailRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateBangbooSupplyDetailRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Bangboo_WS.BangbooSupplyDetail_Service.VO_BangbooSupplyDetails detail;
        
        public CreateBangbooSupplyDetailRequestBody() {
        }
        
        public CreateBangbooSupplyDetailRequestBody(Bangboo_WS.BangbooSupplyDetail_Service.VO_BangbooSupplyDetails detail) {
            this.detail = detail;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateBangbooSupplyDetailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateBangbooSupplyDetailResponse", Namespace="http://tempuri.org/", Order=0)]
        public Bangboo_WS.BangbooSupplyDetail_Service.CreateBangbooSupplyDetailResponseBody Body;
        
        public CreateBangbooSupplyDetailResponse() {
        }
        
        public CreateBangbooSupplyDetailResponse(Bangboo_WS.BangbooSupplyDetail_Service.CreateBangbooSupplyDetailResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateBangbooSupplyDetailResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CreateBangbooSupplyDetailResult;
        
        public CreateBangbooSupplyDetailResponseBody() {
        }
        
        public CreateBangbooSupplyDetailResponseBody(string CreateBangbooSupplyDetailResult) {
            this.CreateBangbooSupplyDetailResult = CreateBangbooSupplyDetailResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBangbooSupplyDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBangbooSupplyDetails", Namespace="http://tempuri.org/", Order=0)]
        public Bangboo_WS.BangbooSupplyDetail_Service.GetBangbooSupplyDetailsRequestBody Body;
        
        public GetBangbooSupplyDetailsRequest() {
        }
        
        public GetBangbooSupplyDetailsRequest(Bangboo_WS.BangbooSupplyDetail_Service.GetBangbooSupplyDetailsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBangbooSupplyDetailsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Bangboo_WS.BangbooSupplyDetail_Service.ArrayOfAnyType parameters;
        
        public GetBangbooSupplyDetailsRequestBody() {
        }
        
        public GetBangbooSupplyDetailsRequestBody(Bangboo_WS.BangbooSupplyDetail_Service.ArrayOfAnyType parameters) {
            this.parameters = parameters;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBangbooSupplyDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBangbooSupplyDetailsResponse", Namespace="http://tempuri.org/", Order=0)]
        public Bangboo_WS.BangbooSupplyDetail_Service.GetBangbooSupplyDetailsResponseBody Body;
        
        public GetBangbooSupplyDetailsResponse() {
        }
        
        public GetBangbooSupplyDetailsResponse(Bangboo_WS.BangbooSupplyDetail_Service.GetBangbooSupplyDetailsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBangbooSupplyDetailsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Bangboo_WS.BangbooSupplyDetail_Service.VO_BangbooSupplyDetails[] GetBangbooSupplyDetailsResult;
        
        public GetBangbooSupplyDetailsResponseBody() {
        }
        
        public GetBangbooSupplyDetailsResponseBody(Bangboo_WS.BangbooSupplyDetail_Service.VO_BangbooSupplyDetails[] GetBangbooSupplyDetailsResult) {
            this.GetBangbooSupplyDetailsResult = GetBangbooSupplyDetailsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BangbooSupplyDetail_ServiceSoapChannel : Bangboo_WS.BangbooSupplyDetail_Service.BangbooSupplyDetail_ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BangbooSupplyDetail_ServiceSoapClient : System.ServiceModel.ClientBase<Bangboo_WS.BangbooSupplyDetail_Service.BangbooSupplyDetail_ServiceSoap>, Bangboo_WS.BangbooSupplyDetail_Service.BangbooSupplyDetail_ServiceSoap {
        
        public BangbooSupplyDetail_ServiceSoapClient() {
        }
        
        public BangbooSupplyDetail_ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BangbooSupplyDetail_ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BangbooSupplyDetail_ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BangbooSupplyDetail_ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bangboo_WS.BangbooSupplyDetail_Service.CreateBangbooSupplyDetailResponse Bangboo_WS.BangbooSupplyDetail_Service.BangbooSupplyDetail_ServiceSoap.CreateBangbooSupplyDetail(Bangboo_WS.BangbooSupplyDetail_Service.CreateBangbooSupplyDetailRequest request) {
            return base.Channel.CreateBangbooSupplyDetail(request);
        }
        
        public string CreateBangbooSupplyDetail(Bangboo_WS.BangbooSupplyDetail_Service.VO_BangbooSupplyDetails detail) {
            Bangboo_WS.BangbooSupplyDetail_Service.CreateBangbooSupplyDetailRequest inValue = new Bangboo_WS.BangbooSupplyDetail_Service.CreateBangbooSupplyDetailRequest();
            inValue.Body = new Bangboo_WS.BangbooSupplyDetail_Service.CreateBangbooSupplyDetailRequestBody();
            inValue.Body.detail = detail;
            Bangboo_WS.BangbooSupplyDetail_Service.CreateBangbooSupplyDetailResponse retVal = ((Bangboo_WS.BangbooSupplyDetail_Service.BangbooSupplyDetail_ServiceSoap)(this)).CreateBangbooSupplyDetail(inValue);
            return retVal.Body.CreateBangbooSupplyDetailResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Bangboo_WS.BangbooSupplyDetail_Service.CreateBangbooSupplyDetailResponse> Bangboo_WS.BangbooSupplyDetail_Service.BangbooSupplyDetail_ServiceSoap.CreateBangbooSupplyDetailAsync(Bangboo_WS.BangbooSupplyDetail_Service.CreateBangbooSupplyDetailRequest request) {
            return base.Channel.CreateBangbooSupplyDetailAsync(request);
        }
        
        public System.Threading.Tasks.Task<Bangboo_WS.BangbooSupplyDetail_Service.CreateBangbooSupplyDetailResponse> CreateBangbooSupplyDetailAsync(Bangboo_WS.BangbooSupplyDetail_Service.VO_BangbooSupplyDetails detail) {
            Bangboo_WS.BangbooSupplyDetail_Service.CreateBangbooSupplyDetailRequest inValue = new Bangboo_WS.BangbooSupplyDetail_Service.CreateBangbooSupplyDetailRequest();
            inValue.Body = new Bangboo_WS.BangbooSupplyDetail_Service.CreateBangbooSupplyDetailRequestBody();
            inValue.Body.detail = detail;
            return ((Bangboo_WS.BangbooSupplyDetail_Service.BangbooSupplyDetail_ServiceSoap)(this)).CreateBangbooSupplyDetailAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bangboo_WS.BangbooSupplyDetail_Service.GetBangbooSupplyDetailsResponse Bangboo_WS.BangbooSupplyDetail_Service.BangbooSupplyDetail_ServiceSoap.GetBangbooSupplyDetails(Bangboo_WS.BangbooSupplyDetail_Service.GetBangbooSupplyDetailsRequest request) {
            return base.Channel.GetBangbooSupplyDetails(request);
        }
        
        public Bangboo_WS.BangbooSupplyDetail_Service.VO_BangbooSupplyDetails[] GetBangbooSupplyDetails(Bangboo_WS.BangbooSupplyDetail_Service.ArrayOfAnyType parameters) {
            Bangboo_WS.BangbooSupplyDetail_Service.GetBangbooSupplyDetailsRequest inValue = new Bangboo_WS.BangbooSupplyDetail_Service.GetBangbooSupplyDetailsRequest();
            inValue.Body = new Bangboo_WS.BangbooSupplyDetail_Service.GetBangbooSupplyDetailsRequestBody();
            inValue.Body.parameters = parameters;
            Bangboo_WS.BangbooSupplyDetail_Service.GetBangbooSupplyDetailsResponse retVal = ((Bangboo_WS.BangbooSupplyDetail_Service.BangbooSupplyDetail_ServiceSoap)(this)).GetBangbooSupplyDetails(inValue);
            return retVal.Body.GetBangbooSupplyDetailsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Bangboo_WS.BangbooSupplyDetail_Service.GetBangbooSupplyDetailsResponse> Bangboo_WS.BangbooSupplyDetail_Service.BangbooSupplyDetail_ServiceSoap.GetBangbooSupplyDetailsAsync(Bangboo_WS.BangbooSupplyDetail_Service.GetBangbooSupplyDetailsRequest request) {
            return base.Channel.GetBangbooSupplyDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Bangboo_WS.BangbooSupplyDetail_Service.GetBangbooSupplyDetailsResponse> GetBangbooSupplyDetailsAsync(Bangboo_WS.BangbooSupplyDetail_Service.ArrayOfAnyType parameters) {
            Bangboo_WS.BangbooSupplyDetail_Service.GetBangbooSupplyDetailsRequest inValue = new Bangboo_WS.BangbooSupplyDetail_Service.GetBangbooSupplyDetailsRequest();
            inValue.Body = new Bangboo_WS.BangbooSupplyDetail_Service.GetBangbooSupplyDetailsRequestBody();
            inValue.Body.parameters = parameters;
            return ((Bangboo_WS.BangbooSupplyDetail_Service.BangbooSupplyDetail_ServiceSoap)(this)).GetBangbooSupplyDetailsAsync(inValue);
        }
    }
}
